### ISSUE TITLE
 open http://localhost:8080/. Error HTTP Status 404-Not Found, and why?

### ISSUE THREAD

**Issue by creamjiang** [docdoku/docdoku-plm#1002]
I deployed the latest version docdoku-Server-ear.ear, no errors, but open http://localhost:8080/. Error HTTP Status 404-Not Found, and why?

**Comment by mguimard** [comment]
The latest version of ear (dev branch) doesn't contain the GUI anymore, but only webservices. You need to run the release 2.0 if you want to have the GUI embedded. We'll soon update the doc to deploy it.

Also, you can have a look to https://github.com/docdoku/docdoku-plm/wiki/Development-Guide and try to get it running.

**Comment by mguimard** [comment]
Yes, run `npm run build` in `docdoku-web-front` to generate the `dist` folder, then use a proxy to connect it.
