### ISSUE TITLE
[Forbidden] Trying to load a forbidden page

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1003]
never ends loading indicator and never shows the forbidden message error.

![screen shot 2016-07-11 at 10 15 46](https://cloud.githubusercontent.com/assets/644898/16723963/792db362-4750-11e6-9f34-7039d8d625de.png)

Should redirect to home page and show the error message.

**Comment by mguimard** [comment]
Should be resolved with ae2489718ab094442149908bd3794ecc1565a91d

**Comment by elisabelgenereux** [comment]
![screen shot 2016-09-22 at 11 50 58](https://cloud.githubusercontent.com/assets/644898/18743844/459e9b8e-80bb-11e6-972a-654a94ec6fa0.png)

**Comment by mguimard** [comment]
closed by 5b926bdf8a59b762e342923e1c70458b6e59d6bf
