### ISSUE TITLE
I uploaded ".obj and .3ds" format files, so why not 3D visualization?

### ISSUE THREAD

**Issue by creamjiang** [docdoku/docdoku-plm#1006]
I uploaded ".obj and .3ds" format files, so why not 3D visualization?

Current 3D conversion plugin configuration successfully. Home login page can see 3D visualizations.

Thank you!

**Comment by mguimard** [comment]
Please provide your 3D files so we can test them

**Comment by creamjiang** [comment]
OK，3D file:

[3Dsucai.zip](https://github.com/docdoku/docdoku-plm/files/359192/3Dsucai.zip)

**Comment by mguimard** [comment]
I'm able to see 2 files in our 3D scene. 
`58pic_53e030ea89bc9.3ds` and `58pic_53e030ea753a6.obj` The 2 other files seems to be corrupted, (only 240 bytes, and no 3D data inside) 

To visualize your files : 

1. Create a part
2. Upload one of your files
3. You should have  "Conversion succeed" message
4. Click on the title at the top of the modal (permalink)
5. Open the CAD file tab, you should see it

**Comment by creamjiang** [comment]
Thank you very much!
