### ISSUE TITLE
[Checked out link] badge number color

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1018]
not consistent between documents (always gray) and parts (blue or green)

![screen shot 2016-07-22 at 16 54 28](https://cloud.githubusercontent.com/assets/644898/17061071/ff934f90-502c-11e6-82a4-2b6958326230.png) ![screen shot 2016-07-22 at 16 55 29](https://cloud.githubusercontent.com/assets/644898/17061090/22d20b0e-502d-11e6-930c-11e21abe9ff7.png)

**Comment by mguimard** [comment]
closed by 2d26f11a960f727e5a945195ec38adfcbdf853d4
