### ISSUE TITLE
[Query builder] Disable actions buttons

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1022]
Steps to reproduce:

* check one ore several parts in the parts list

* open the query builder section

* build a query and search for the results

* the actions buttons remains displayed and active whereas the user does not see its selection anymore

![screen shot 2016-08-03 at 10 01 59](https://cloud.githubusercontent.com/assets/644898/17358276/5a904262-5961-11e6-9daa-0cb372dd658f.png)

**Comment by mguimard** [comment]
closed by 984e814f5b2c13ec4371ae2d74f929c036f9d1c4
