### ISSUE TITLE
[THIRD LIB] dependencies

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#1033]
Some third lib dependencies (jquery.treeview.css, font-awesome.min.css...) are not manage with a package manager (npm, bower...) but directly stored as other source code.
Could it be possible to change that?

**Comment by mguimard** [comment]
Only 2 libs left : 
- Helvetiker regular typeface
- plugin detect (doesn't seem to be available in package managers)

**Comment by mguimard** [comment]
See https://github.com/docdoku/docdoku-web-front/issues/6 and https://github.com/docdoku/docdoku-web-front/blob/dev/NOTICE.txt for front web app third libs related issues.
