### ISSUE TITLE
[Super admin] Dashboard js errors

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1045]
![screen shot 2016-09-06 at 16 38 10](https://cloud.githubusercontent.com/assets/644898/18277909/7baa4c22-7450-11e6-8513-faa6f6ee6613.png)

We should only display the graph Users if the super admin has only the admin role and does not belong to any workspace

**Comment by mguimard** [comment]
Fixed in 9152bdf6d0ef6439884e808ef1297c578f49161c
