### ISSUE TITLE
[Workspace management] change administrator

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1046]
Add the interface (input + button) to enable the current workspace admin to give the lead to another user

WS already exists (WorkspaceResource.setNewAdmin)

**Comment by defmsy** [comment]
Issue solved in [docdoku/docdoku-web-front](https://github.com/docdoku/docdoku-web-front) repository by [this commit](https://github.com/docdoku/docdoku-web-front/commit/d311fd7d4458349fc4fb45d6cb16d59cc30501f4)
