### ISSUE TITLE
Debian install - Can't deploy app

### ISSUE THREAD

**Issue by LeOSW42** [docdoku/docdoku-plm#1050]
Hi all !

I'm trying to install docdokuplm on a Debian Jessie server.

My configuration is:

- openjdk-8-jdk 8u102 (jessie backports)
- Glassfish 4.0 (manual install)
- mysql-server 5.6.30 (jessie backports)
- libmysql-java 5.1.39 (jessie backports)
- libreoffice 4.3.3 (jessie)
- freecad 0.16 (jessie backports)
- elasticsearch 2.2.0 (elasticsearch repository)

Everything worked except I've skipped the mail configuration and the libreoffice configuration in the ear file.
Once everything configured, I try to deploy the 2.0 provided binary ear file as an Enterprise Application.

I have that error:

` Error occurred during deployment: Exception while deploying the app [docdoku-server-ear] : UnsupportedClassVersionError: Class com.docdoku.server.esindexer.ESSearcher has unsupported major or minor version numbers, which are greater than those found in the Java Runtime Environment version 1.7.0_111. Please see server.log for more details. `

I've tried to build from source but npm is not able to find less_elements from git (404 error).

Léo :fr:

**Comment by florentgarin** [comment]
Hi Léo,

For your first remark, It seems for me that your are using Java 1.7.0_111 not openjdk-8-jdk 8u102 as you thought.
Can you please check carefully that point?

For the second one, which branch are you trying to compile?

**Comment by LeOSW42** [comment]
Ok you're right. I didn't changed the java's alternatives. Thanks.

**Comment by rudi123** [comment]
How do you changed the java's alternatives?
