### ISSUE TITLE
[Tag Subscription] Unhandled system error

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#1054]
Steps to reproduce:
- try to delete a tag associated with a tag subscription

sun.reflect.NativeConstructorAccessorImpl.newInstance0 threw com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`docdokuplm`.`tagusergroupsubscription`, CONSTRAINT `FK_TAGUSERGROUPSUBSCRIPTION_TAG_LABEL` FOREIGN KEY (`TAG_LABEL`, `TAG_WORKSPACE_ID`) REFERENCES `TAG` (`LABEL`, `WORKSPACE_ID`)) in NativeConstructorAccessorImpl.java at line -2

**Comment by elisabelgenereux** [comment]
display a human message error on interface

**Comment by mguimard** [comment]
closed by f573369f6e9d127bf1d791544e509810a4fbc397
