### ISSUE TITLE
[WORKFLOW] doesn't go forward

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#1062]
workflow get stuck and don't progress Forward

**Comment by florentgarin** [comment]
The problem is due to the fact that DocumentWorkflowManagerBean.approveTaskOnDocument the loaded task is not the one that belongs to the workflow.
More precisely the activity of the task doesn't belong to the workflow.
 
This problem has been fixed on V2.5 but that fix is not totally satisfying because the original error is not on the approveTaskOnDocument but inside the method where the workflow has been created.
On that method the bi directional link is properly maintained.

**Comment by mguimard** [comment]
closed by ad9c948c6960a41ec1608cfc75e7d170fbc4d6ed
