### ISSUE TITLE
[WORDING] on approving or rejecting task on part

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#1064]
"Vous ne pouvez pas marquer une tâche comme effectuée ou la rejeter sur un document réservé"

The same in english but it can concerned also a part...

**Comment by florentgarin** [comment]
![capture du 2016-09-30 19-22-11](https://cloud.githubusercontent.com/assets/868602/19000566/888fdd34-8743-11e6-9c6a-193476ac3903.png)

**Comment by mguimard** [comment]
This message seems correct:

EN:

    NotAllowedException16=You cannot mark a task as done or reject it on a document which is checked out
    NotAllowedException17=You cannot mark a task as done or reject it on a part which is checked out

FR:

    NotAllowedException16=Vous ne pouvez pas marquer une t\u00e2che comme effectu\u00e9e ou la rejeter sur un document r\u00e9serv\u00e9
    NotAllowedException17=Vous ne pouvez pas marquer une t\u00e2che comme effectu\u00e9e ou la rejeter sur un article r\u00e9serv\u00e9

**Comment by florentgarin** [comment]
fixed
