### ISSUE TITLE
[Tags] Read-only user remove or add existing tags

### ISSUE THREAD

**Issue by mfrederic** [docdoku/docdoku-plm#1065]
On documents and parts, a read-only user can visually remove tags by clicking on the left cross to each tags. They also can visually add created or existing tags.

<img width="400" alt="capture d ecran 2016-10-05 a 16 28 34" src="https://cloud.githubusercontent.com/assets/3066614/19117295/cb87f986-8b18-11e6-9e7b-42a8b8d51f79.png">

When the user try to save modifications, the console show a 403 error and not saving tags updates. Read-only users shouldn't have the possibility to interact with tags.

**Comment by mguimard** [comment]
related to #450

**Comment by mfrederic** [comment]
Resolve in commit c9c1197d15824ba45475e51ef9c38b8e0d6e4d22
Fix reported to Release-2.0 in commit 8465954841909c6707bdee407447849232a361ee
