### ISSUE TITLE
[Account creation] Account creation form doesn't appear on Google Chrome

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#1093]
When clicking on "Sign up" link on the home page, the account creation form doesn't appear on Google Chrome (Version 57.0.2987.133). It's OK on FF.

**Comment by mguimard** [comment]
Seems that localStorage is not cleared in some cases (jwt is sent while it shoudn't be). Please clear offline data from chrome://settings/cookies and try again until we find the cause.

**Comment by ericdescargues** [comment]
OK tested, it works after cleaning.

**Comment by mguimard** [comment]
fixed by https://github.com/docdoku/docdoku-web-front/commit/53e855f52015cf2a35de7f8c312740546c9f8cae
