### ISSUE TITLE
[Instance attributes] Error when adding new attributes

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#1094]
When trying to modify an instance by adding new attributes, I have this error:

org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects threw java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: . in RepeatableWriteUnitOfWork.java at line 31

cf screenshot too.
![instance-update-attributes](https://cloud.githubusercontent.com/assets/1931399/24961059/ec61ac92-1f97-11e7-842c-d5ec79a0e724.png)

**Comment by mguimard** [comment]
The error comes from the non-existence of the part "66", you're only allowed to link existent parts.
By the way, the error message doesn't really help, and should be modified.

**Comment by mguimard** [comment]
Linked to #1069
