### ISSUE TITLE
[AUTH] role

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#1097]
ctx.isCallerInRole(String role)does not return the correct value constantly.
Not sure to get the proper scenario any way.

**Comment by florentgarin** [comment]
Actually the JWT is not sent...

**Comment by florentgarin** [comment]
One more precision it seems that the scene loader which does not send it.

**Comment by mguimard** [comment]
What is the CAD file extension ? according to this link, token seems to be correctly set in headers from different CAD files loaders : https://github.com/docdoku/docdoku-web-front/search?utf8=%E2%9C%93&q=bearer

**Comment by florentgarin** [comment]
The extension is ".json".

**Comment by mguimard** [comment]
Right, it seems that the token is not sent from the JSONLoader. Moving the issue to dedicated repository.

**Comment by florentgarin** [comment]
Expiration seems to be the same. I got a case when JSONLoader did not send the token whereas other XHR request can correctly performed.

**Comment by mguimard** [comment]
This must be fixed now for JSONLoader and other modules sending HTTP requests
