### ISSUE TITLE
[Collaborative Session] Rest API

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#1098]
Why not change from POST to GET when sending body request like elasticsearch for instance?

**Comment by mguimard** [comment]
ElasticSearch QueryDSL actually does the opposite (from GET to POST)

Related to #330 ?

**Comment by florentgarin** [comment]
Elasticsearch recommends using GET with body.  
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

**Comment by mguimard** [comment]
They do not recommend it, this is simply an exemple. They allow the search API to be requested with GET or POST methods.

The HTTP specification doesn't restrict the usage of body requests with GET methods, then yes, it is possible to switch our service from POST to GET. 

However I don't think this will be useful. We won't benefit from cache from the application server, and even worse, proxies could interfere by caching the response if they do not handle GET requests with a body.

**Comment by florentgarin** [comment]
Actually they both have their pros and cons. GET has the advantage to offer a better semantic but it has also disadvantages as you mentioned.
I said they recommend GET because I read an "official" statement from them saying that.
Ok, we can keep as it is.
