### ISSUE TITLE
BinaryResource fullName is too short 

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#1099]
A team member from a project using our API had an issue with the BinaryResource fullName size. By default, it's 255 characters long. Some paths can be much longer. Should we use @Lob annotation for this field ?

**Comment by florentgarin** [comment]
There can be performance impact that must be check before.

**Comment by jzanon** [comment]
Temporary workaround for PostgreSQL DB:

`ALTER TABLE BINARYRESOURCE ALTER COLUMN FULLNAME TYPE VARCHAR(512) USING FULLNAME::VARCHAR(512);`

**Comment by mguimard** [comment]
I think you need to alter some more tables that reference that key:
    
    DOCUMENTITERATION_BINRES
    DOCUMENTMASTERTEMPLATE_BINRES
    PARTITERATION_BINRES
    PATHDATAITERATION_BINRES
    PRDINSTITERATION_BINRES
    
If that doesn't affect performances I think we'll go that way and modify the BinaryResource 
(FYI, InnoDB doesn't accept more than 767 bytes for index key prefix)

**Comment by jzanon** [comment]
It is not required on PostgreSQL.

On MySQL, yes. It's needed to: drop FK constraints, alter table, re-create
FK & indexes.

Le ven. 11 août 2017 18:50, Morgan Guimard <notifications@github.com> a
écrit :

**Comment by jzanon** [comment]
Solution impemented by @florentgarin : https://github.com/polarsys/eplmp/commit/1fe39a0d18e5b35a292b8d344c535176d8f3abaf
