### ISSUE TITLE
RU Localisation

### ISSUE THREAD

**Issue by sah4ez** [docdoku/docdoku-plm#1100]
Hi!
Tell me what I need to do to localize to another language?

**Comment by florentgarin** [comment]
Hi,

On the server side core project (docdoku/docdoku-plm) you need to create files for your language for:

LocalStrings.properties (for an example look at LocalStrings_fr.properties for french)
MailText.properties

On the client side (docdoku/docdoku-web-front project) you need to add files your your language under the folder:

/app/js/localization

Look for existing supported languages as a example.

**Comment by mguimard** [comment]
Hello, 

A docker-compose project has been created for development pruposes, you can give a try to https://github.com/docdoku/docdoku-plm-docker 

Also, branch `feature-ru-translation` is ready to be forked, it contains 5 new files `*_ru.properties` that need to be translated.

Thank you for contributing !

**Comment by sah4ez** [comment]
Hi,
I begined translation.

**Comment by sah4ez** [comment]
I all translated and begined testing.

**Comment by sah4ez** [comment]
#1106
