### ISSUE TITLE
Can I bulk import part CAD? Not at the moment.

### ISSUE THREAD

**Issue by creamjiang** [docdoku/docdoku-plm#1103]
Can I bulk import part CAD? Not at the moment.

I click on the standard parts -> import, but cannot import CAD.

**Comment by mguimard** [comment]
Hi,

Right, currently there is no bulk import.

What is the file format of your CAD files ? See https://github.com/docdoku/docdoku-plm/wiki/Convert-Plugins for CAD file support

To upload your CAD files you need to open the part window (by clicking its part number), then use the Files tab and drop your CAD file in the first zone.

![image](https://user-images.githubusercontent.com/3205135/27542904-ec6ce158-5a88-11e7-9b06-f627dd37ba41.png)

**Comment by creamjiang** [comment]
can support SolidWorks, CATIA format convert plugins, need license? How to get it?

**Comment by mguimard** [comment]
This is non-free software, please contact our sales department https://en.docdoku.com/identity/contact/ for pricing information
