### ISSUE TITLE
Assembly and Part

### ISSUE THREAD

**Issue by sah4ez** [docdoku/docdoku-plm#1104]
Hi, when I translated back-end, I had a question: 
Do you have an assembly understanding for many parts in the one part? Or you using a part understanding for a single-part and a multi-part files?

**Comment by mguimard** [comment]
Hi, the word we commonly use for parts having children parts (components) is "assembly", and we use "part" for parts that have no components. This message illustrates it well:

    EntityConstraintException2=You cannot delete a part used as component in an assembly

**Comment by sah4ez** [comment]
I found only 3 space with "assembly"... 
Example:
``PartIterationNotFoundException=The part "{0}" revision "{1}" iteration "{2}" or its sub-elements have not been found``
`sub-elements` - it's children part? Or it's feature of CAD-file tree?

**Comment by mguimard** [comment]
This is a very generic message. It can be children parts, attributes, cad and attached files, links, etc..

**Comment by sah4ez** [comment]
ok, thanks.
