### ISSUE TITLE
Upload large file conversion failed. Why? 

### ISSUE THREAD

**Issue by creamjiang** [docdoku/docdoku-plm#1109]
Upload large file conversion failed. Why? How can I upload large files quickly?

**Comment by mguimard** [comment]
> Upload large file conversion failed. Why? How can I upload large files quickly?

What is the CAD file format ? Please share it.
What is its size ?
Any logs ?

**Comment by creamjiang** [comment]
300MB CAD file, upload after conversion failed. No logs. Can I upload large files in other ways?

**Comment by florentgarin** [comment]
There is no limit on the size of attached file, that should work. At least if you properly setup the HTTP service as explained there:
https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide

Otherwise, please share the CAD file if possible so we can check what really happen.

**Comment by creamjiang** [comment]
"Thread interrupted: java.lang.InterruptedException"
Such a error. How do I set payara server parameters?
http://www.51cloudmade.com/bwj.stp
