### ISSUE TITLE
[Permalink] Impossible to view and download files

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#1110]
On Firefox, it's impossible to download a file (nothing happens) and to view a file in the browser (HTTP Status 401 - Unauthorized).

On Goggle Chrome, it shows 2 download at he first time the file is downloaded.  
=> perhaps browsers don't like to download files ahead of time ?

**Comment by mguimard** [comment]
I cannot reproduce the bug. Can you please provide the link to the concerned document (or part) ?

**Comment by florentgarin** [comment]
One important precision the issue happen when accessing the permanent link through a shared link (password protected actually).

**Comment by mguimard** [comment]
I can reproduce it with password protected resources, there are many problems (headers restricted by our CORS policy, the way we provide the uuid for files (should be in query params), and the way we try to access it on server side)
