### ISSUE TITLE
Localization RU

### ISSUE THREAD

**Issue by sah4ez** [docdoku/docdoku-plm#1114]
Hi,
when I saved workflow, I had bad workflow ID `?????1`, state names and final state it.
For state names and final state it I re-enter on Russian and all saved correct. 
I think need add support of localization to DB.

**Comment by mguimard** [comment]
Hi @sah4ez 

You have to specify charset and collate if your database engine use an other default configuration.

    CREATE DATABASE docdokuplm
      DEFAULT CHARACTER SET utf8
      DEFAULT COLLATE utf8_general_ci;

**Comment by sah4ez** [comment]
Thank for answer.
I try check it soon.

**Comment by mguimard** [comment]
Closing issue, please reopen if needed.
