### ISSUE TITLE
Unhandled error on part deletion (effectivity constraints)

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-plm#1123]
Error while removing a product when the root part of the product has attached effectivity and show an exception to the user; sometimes after deleting every effectivity, the problem still persist.

Unhandled system error : sun.reflect.NativeConstructorAccessorImpl.newInstance0 threw com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`devdocdokuplm`.`PARTREVISION_EFFECTIVITY`, CONSTRAINT `FK_PARTREVISION_EFFECTIVITY_EFFECTIVITY_ID` FOREIGN KEY (`EFFECTIVITY_ID`) REFERENCES `EFFECTIVITY` (`ID`)) in NativeConstructorAccessorImpl.java at line -2

**Comment by mguimard** [comment]
Are you sure you are trying to remove a product ? It seems that you are trying to remove a part.

**Comment by mguimard** [comment]
Confirmed. This happens when trying to delete a part that has effectivities.

**Comment by mguimard** [comment]
When deleting a part, we should insure that it has no effectivities. If some effectivities are attached to the part, send a comprehensive message to the end user.
