### ISSUE TITLE
Upgrade Dozer dependency to avoid hardcoded SLF4J Binding

### ISSUE THREAD

**Issue by jzanon** [docdoku/docdoku-plm#1128]
This issue is relative to Dozer issue: https://github.com/DozerMapper/dozer/issues/98

A **workaround** has been applied with: https://github.com/polarsys/eplmp/pull/1

Dozer lib should be upgraded to 5.5.0+ (minimum).

**Comment by mguimard** [comment]
https://github.com/polarsys/eplmp/pull/1/files
