### ISSUE TITLE
[Full screen] Canvas not resized on 3D viewer

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#1143]
Only on Google Chrome (64.0.32), not reproduced on FF (58.0.2).
Canvas is not resized when trying to display a 3D full screen view of a product.

**Comment by mguimard** [comment]
Cannot reproduce with the latest chrome version (67.0.3396.87)

**Comment by mguimard** [comment]
@Hunsu please try and close if not reproductible on latest chrome

**Comment by Hunsu** [comment]
Can't reproduce.
