### ISSUE TITLE
Decoding/parsing of query string for advanced search

### ISSUE THREAD

**Issue by ymerghoub** [docdoku/docdoku-plm#1144]
This issue is correlated with issue []https://github.com/docdoku/docdoku-web-front/issues/50 of docdoku-web-front project. As explained there, when query string is encoded as a whole in client side, decoding/parsing in server side leads to issues like '+' char decoded into espace, confusion between '&' as param separator and '&' as included in the term to search, and so on.
Furthermore, ';' and ':' must be unescaped to distinguish  between these two characters as delimiters in attributes search and as characters included in terms to be searched.

**Comment by Hunsu** [comment]
Fixed by this https://github.com/polarsys/eplmp/commit/555cfc99455dc7d1858e5f9275b2c89a865f1364
