### ISSUE TITLE
No CAD converter able to handle abc.stl file

### ISSUE THREAD

**Issue by paragsahu** [docdoku/docdoku-plm#1152]
I have installed docdokuplm 2.5 on my system(Ubuntu 16.04). I am not able to convert .stl cad file into .obj format. I have used meshconv converter plugin. Also I have set the path in /opt/meshconv/meshconv.
Still I am getting "NO CAD converter able to handle .stl file  
![photo_2018-05-25_10-44-37](https://user-images.githubusercontent.com/33711745/40527181-acd5e3ce-6008-11e8-8acc-56b04fc45197.jpg)

Also in server.log file of payara server i am getting this error message
![photo_2018-05-25_10-50-27](https://user-images.githubusercontent.com/33711745/40527487-6a22a632-600a-11e8-8cad-4b21f063cefd.jpg)

**Comment by mguimard** [comment]
Hello, something is missing in the wiki.

You have to deploy the following EAR in the same payara domain folder : `converter-all/converter-all-ear/target/converter-all-ear-2.5-SNAPSHOT`.

For other converters, you also need to deploy other EARs

**Comment by paragsahu** [comment]
hello sir ,
we did the same as you said just now , but same issue is still persist.
also i found @CADConvert annotation is missing in ConverterBean.java ....
Is it necessary to add this annotation ?

![photo_2018-05-25_13-02-31](https://user-images.githubusercontent.com/33711745/40532090-f72bd90c-601b-11e8-91d9-c3893848f400.jpg)

please tell us the solution as soon as possible.

**Comment by mguimard** [comment]
I forgot to mention that you need to restart the payara domain.

**Comment by paragsahu** [comment]
yes....now its converting but I am able to see only preview of that file. 
Its not visualizing file in  assembly option and also in  "visualize product" option

 
![3d](https://user-images.githubusercontent.com/33711745/40542261-1b3b532e-603d-11e8-83ac-323bb6f82980.png)

**Comment by paragsahu** [comment]
Thanks you so much,
Now docdokuPLM is up and  running in my PC.
