### ISSUE TITLE
Unable to access Docdokuplm using url 

### ISSUE THREAD

**Issue by DRDL** [docdoku/docdoku-plm#1158]
Hi team ,

As I am new to the plm software as i need to deploy Docdokuplm, i have successfully deployed the application which was downloaded from website in to the Payara 5.1 server but i am unable to access it  through the  URL.

Kindly help me with some corrections.... Awaiting for the response with ease .

Followed these URL:

https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide 
https://github.com/docdoku/docdoku-plm/wiki/Software-Configuration

I am attaching the server.log file of payara server such that you can have a clear picture of what has exactly happened .

[server.log](https://github.com/docdoku/docdoku-plm/files/2154579/server.log)

**Comment by defmsy** [comment]
Hi and welcome.
First I advise you to switch to Payara 4.1 which is the current supported version. Payara 5 is not currently properly supported.

**Comment by DRDL** [comment]
I will check and update the same

**Comment by DRDL** [comment]
Exception  while deploying the app [docdoku-server-ear] : Referencing error: this  bundle has no bean of name: MailerBean. Please see server.log for more  details.

I am getting this error unable to trace out the problem can you help please 

[server.log](https://github.com/docdoku/docdoku-plm/files/2158504/server.log)

**Comment by DRDL** [comment]
Anyone can help .. Waiting for the reply...

**Comment by DRDL** [comment]
Please can anyone respond to this issue.... I need to tale this to the production environment.

**Comment by ksupriyasingh** [comment]
is there any community support forum of docdokuplm..even i am facing some issues while building the project but there is no one to respond?
#1162 #1161

**Comment by DRDL** [comment]
Don't know this is the only link and forum i have got the reply

**Comment by ksupriyasingh** [comment]
can you help me to build this project..i cloned the docdokuPLM project from its repository and trying to build the project with 'mvn clean install' but i am getting error in 'docdoku-api-js' module.. do i need any configuration or any separate software for this module..i have not done any configuration i have just cloned and directly trying to build
![build_failure](https://user-images.githubusercontent.com/29394074/42490648-1d49b28a-842f-11e8-8f24-ea2125713e95.PNG)

**Comment by ksupriyasingh** [comment]
how can i deploy this project into wildfly 10 server..if anyone have any idea regarding this then please help..

**Comment by DRDL** [comment]
If anyone online please reply for this .

**Comment by mguimard** [comment]
Hi, sorry we don't bring support for glassfish 4.0, your best chance is to use payara full 4.1.2.181. Also, please make sure to follow the installation guide in the wikis.

**Comment by SUMANG484** [comment]
I have changed my payara full to 4.1.2.181 and i have deployed the application into the web server . Unable to access my application from URL .Can you please suggest me its an humble request . Attaching my log files please check and update as i need to take this to live please help me on the same 
[server.log](https://github.com/docdoku/docdoku-plm/files/2234452/server.log)

**Comment by mguimard** [comment]
Your logs are very fine. The application (web services) should be available at http://localhost:808/eplmp-server-rest/api. Please read the wiki and also have a look at https://github.com/docdoku/docdoku-web-front
