### ISSUE TITLE
facing issues while building project

### ISSUE THREAD

**Issue by ksupriyasingh** [docdoku/docdoku-plm#1161]
![docdukeplm](https://user-images.githubusercontent.com/29394074/42375936-ed07967e-813a-11e8-861a-dbd791a76ebb.PNG)

Cloned the project and i am trying to build but i am facing this build failure. DO i have any kind of configuration to build

**Comment by mguimard** [comment]
Hello, please refer to https://github.com/docdoku/docdoku-plm/wiki/Software-Configuration (npm missing)
