### ISSUE TITLE
Configuration with postgresql and JBoss wildfly 10

### ISSUE THREAD

**Issue by ksupriyasingh** [docdoku/docdoku-plm#1162]
How to configure this application in JBoss wildfly 10 and postgresql, i am unable to find anything related to this please suggest.. i am using windows OS
please help @florentgarin

**Comment by mguimard** [comment]
Hello, sorry we don't bring support for running DocDokuPLM in JBoss, and we wont guaranty it will run.

Please have a look at the JBoss administration guide and try to adapt the server configuration if you really wish to deploy  DocDokuPLM in JBoss.
