### ISSUE TITLE
Unable to change the parameter for "applocation" of the default application which was given by docdokuplm 

### ISSUE THREAD

**Issue by SUMANG484** [docdoku/docdoku-plm#1168]
I need the parameter value "${com.sun.aas.instanceRootURI}/applications/__internal/docdoku-server-ear/docdoku-server-ear2312771665454756650.ear" to change "_____________" and give me the changes to me made after the successful deployment of the default docdokuplm application.
![screenshot from 2018-07-24 16-42-11](https://user-images.githubusercontent.com/29192184/43136194-96b8ab94-8f65-11e8-9986-267e5dd8b0d1.png)

**Comment by SUMANG484** [comment]
and how can i access the application through URL from browser?

**Comment by SUMANG484** [comment]
Anyone please reply me on this ???

**Comment by SUMANG484** [comment]
hello anyone please reply on the same....

**Comment by mguimard** [comment]
Please read carefully https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide and https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide and try again from scratch.

This issue tracker is dedicated for bugs and feature on the code, not for installation support. Closing issue.
