### ISSUE TITLE
Unable to access application through the URL 

### ISSUE THREAD

**Issue by SUMANG484** [docdoku/docdoku-plm#1169]
I have changed my payara full to 4.1.2.181 and i have deployed the application into the web server . Unable to access my application from URL .Can you please suggest me its an humble request . Attaching my log files please check and update as i need to take this to live please help me on the same
[server.log](https://github.com/docdoku/docdoku-plm/files/2234456/server.log)

**Comment by SUMANG484** [comment]
anyone please reply

**Comment by mguimard** [comment]
Once again, this is not a support forum or whatever. This bug tracker is for bugs or features in our code. If you need support to bring it to production, read the docs or contact our sales.

The response is in the docs.

> By default, the port is 8080, but you can change it from there: Configurations > server-config > Network Config > Network Listeners > http-listener-1

We'll directly close any other similar issue
