### ISSUE TITLE
Wrong value accepted for field language  in [PUT /admin/accounts/] service

### ISSUE THREAD

**Issue by ludoBarel** [docdoku/docdoku-plm#1172]
When trying to update the account, i've put 'french' as value for language field, normally this never should be accepted and generate an error. Only 'fr', 'en' and 'ru' must be accepted.

**Comment by mguimard** [comment]
https://github.com/polarsys/eplmp/commit/4dc7ab56d91ec0a4844af5c4621e4bde618c30ae
