### ISSUE TITLE
Erroe while building the docdoku-plm 

### ISSUE THREAD

**Issue by ksupriyasingh** [docdoku/docdoku-plm#1174]
Getting the following error while trying to build the project, firstly i buid the eplm project after i am trying to build this project

![image](https://user-images.githubusercontent.com/29394074/43898357-3332c4da-9bfc-11e8-9555-7dc3a181da89.png)

**Comment by mguimard** [comment]
Serems that you're not building eplmp from the develop branch

**Comment by ksupriyasingh** [comment]
yes, now i am able to build, but i need to deploy it in wildfly 10 server, and now i am getting this error 
![image](https://user-images.githubusercontent.com/29394074/45009977-b9f7b800-b028-11e8-90d5-e4f2ade7754c.png),is there anything i am missing??

**Comment by mguimard** [comment]
Hello, thank you for the feedback. We dont bring support for running
docdokuplm in jboss. If you really want to deploy in jboss I guess your
best chance is to look for similar issues and fix the code that prevents
the app to be deployed.
Closing issue.
Close #1174
