### ISSUE TITLE
Error 500 when tried to manage organisation 

### ISSUE THREAD

**Issue by ludoBarel** [docdoku/docdoku-plm#1186]
When i've tried to manage 'organization' with a 'admin' user  using the following request : 

`[ GET ]  http://localhost:8080/eplmp-server-rest/api/organizations`  

I've received this HTTP response  : 

`HTTP/1.1 500 Internal Server Error
Server: Payara Server  4.1.2.181 #badassfish
X-Powered-By: Servlet/3.1 JSP/2.3 (Payara Server  4.1.2.181 #badassfish Java/Oracle Corporation/1.8)
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: origin, content-type, accept, authorization, x-accept-encoding, password
Access-Control-Expose-Headers: jwt, x-archive-content-length, shared-entity-token, entity-token
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
Reason-Phrase: Unhandled system error : fish.payara.microprofile.jwtauth.jaxrs.RolesAllowedRequestFilter.filter threw javax.ws.rs.ForbiddenException: Caller not in requested role in RolesAllowedRequestFilter.java at line 110`

**Comment by ludoBarel** [comment]
Is the admin user have permission for that? it's seem to not be the case in the implementation of organization class. If  it's not the case i think it's a bug because an exception is raising but interface never stop trying get the related data. With 'curl' tool i've noticed than the displayed message is the exception message i think is not comprehensible message by a lambda user.

**Comment by mguimard** [comment]
I see 2 main problems.

* From the front app, the platform administrator shoudn't have an "organization" button. He's not allowed to be a member of any organization.
* In the server app (resource layer), there is currently no ExceptionMapper class for javax.ws.rs.ForbiddenException. It should be added to avoid such error messages.
