### ISSUE TITLE
Error Message trouble 

### ISSUE THREAD

**Issue by ludoBarel** [docdoku/docdoku-plm#1188]
When i've tried to validate a task in task section without opened the related document and tried to validate or reject it there is no error displayed, but when i'm looked into network console from firefox i've noticed than and error with status code 400 appear and the message was not displayed in the screen.

Related link :  [ PUT ]`http://localhost:8080/eplmp-server-rest/api/workspaces/wks-7678bd94/tasks/109-0-1/process` 

screen shoot : 

![capture d ecran de 2018-08-27 15-10-43](https://user-images.githubusercontent.com/41987769/44661778-05e4a480-aa0c-11e8-9877-eb1c7e2b7447.png)

**Comment by mguimard** [comment]
An error message must be displayed above the lifecycle view. I will try to reproduce.

**Comment by mguimard** [comment]
Cannot reproduce, the error message is displayed. Can you please try to reproduce and describe every single step ?

**Comment by ludoBarel** [comment]
in fact, this not a bug sorry.The message was hide in up side of the frame. it've Need to scroll to up in order to see the message. Just saw that now. I'm closing the issue.
