### ISSUE TITLE
Demo site account not created.

### ISSUE THREAD

**Issue by nikilmethew** [docdoku/docdoku-plm#1205]
BASE URL: https://docdokuplm.net/
 
  Is the above Url a demo site for Docdokuplm?

  We have been trying to register in the above site, we are not getting the registration confirmation mail and have checked the same in multiple Gmail accounts.

  How can we check your demo site?

Kindly let us know how to check with Demo Site.

**Comment by florentgarin** [comment]
Sorry but github is not a help desk software.
You can contact the team you are looking there:
https://www.docdokuplm.com/contact-us/
