### ISSUE TITLE
Table 'docdoku.providedaccount' doesn't exist

### ISSUE THREAD

**Issue by beixs** [docdoku/docdoku-plm#1231]
Hi, 
I installed the latest version and register a new account, but when I login with the new accout, it failed, the error message in server.log is like :
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.payara-p3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'docdoku.providedaccount' doesn't exist
Error Code: 1146

I checked the database, there is no table named 'providedaccount',  what should I do? Is it a bug?

BTW, is there any super user account in Docdoku?  The table 'account' is empty after installation.

Thx

**Comment by florentgarin** [comment]
providedaccount table should be there. Do you have all the other tables?

**Comment by beixs** [comment]
> providedaccount table should be there. Do you have all the other tables?

Thx, florentgarin, now table list in database is :

"account"
"acl"
"aclusergroupentry"
"activity"
"activity_relaunch"
"activitymodel"
"activitymodel_relaunch"
"attribute_namevalue"
"baselineddocument"
"baselinedpart"
"cadinstance"
"changeissue"
"changeissue_affected_document"
"changeissue_affected_part"
"changeissue_tag"
"changeorder"
"changeorder_affected_document"
"changeorder_affected_part"
"changeorder_changerequest"
"changeorder_tag"
"changereq_affected_document"
"changereq_affected_part"
"changerequest"
"changerequest_changeissue"
"changerequest_tag"
"configurationitem"
"configurationitem_p2plink"
"conversion"
"credential"
"document_aborted_workflow"
"documentbaseline"
"documentcollection"
"documentiteration"
"documentiteration_attribute"
"documentiteration_documentlink"
"documentlink"
"documentlog"
"documentmaster"
"documentmastertemplate"
"documentmastertemplate_attr"
"documentrevision"
"effectivity"
"gcmaccount"
"import"
"import_error"
"import_warning"
"instanceattribute"
"instanceattributetemplate"
"layer"
"layer_marker"
"lov"
"lov_namevalue"
"marker"
"marker_effectivity"
"marker_partmaster"
"milestone"
"modificationnotification"
"oauthprovider"
"organization"
"part_aborted_workflow"
"partcollection"
"partiteration"
"partiteration_attribute"
"partiteration_documentlink"
"partiteration_partusagelink"
"partiteration_pathdata_attr"
"partlog"
"partmaster"
"partmaster_alternate"
"partmastertemplate"
"partmastertemplate_attr"
"partmastertpl_instance_attr"
"partrevision"
"partrevision_effectivity"
"partsubstitutelink"
"partsubstitutelink_cadinstance"
"partusagelink"
"partusagelink_cadinstance"
"passwordrecoveryrequest"
"pathdataiteration"
"pathdataiteration_attribute"
"pathdataiteration_documentlink"
"pathdatamaster"
"pathtopathlink"
"platformoptions"
"prdcfg_optionallink"
"prdcfg_substitutelink"
"prdinstanceiteration_optlink"
"prdinstanceiteration_sublink"
"prdinstiteration_attribute"
"prdinstiteration_documentlink"
"prdinstiteration_p2plink"
"prdinstiteration_pathdatamstr"
"productbaseline"
"productbaseline_optionallink"
"productbaseline_p2plink"
"productbaseline_substitutelink"
"productconfiguration"
"productinstanceiteration"
"productinstancemaster"
"pusagelink_psubstitutelink"
"query"
"query_grouped_by"
"query_order_by"
"query_selects"
"querycontext"
"queryrule"
"queryrule_values"
"role"
"tag"
"task"
"task_usergroup"
"taskmodel"
"usergroup"
"usergroupmapping"
"webhook"
"webhookapp"
"workflow"
"workflowmodel"
"workspace"
"workspace_aborted_workflow"
"workspace_documenttablecolumn"
"workspace_parttablecolumn"
"workspace_workflow"
"workspacebackoptions"
"workspacefrontoptions"
"workspacelog"
"workspaceusergroupmembership"

**Comment by florentgarin** [comment]
Which database are you using?

**Comment by beixs** [comment]
mysql 5.7 

> Which database are you using?

**Comment by beixs** [comment]
Got the reasen.
Mysql engine should be set to INNODB but not MyISAM.
