### ISSUE TITLE
Type of binary resource

### ISSUE THREAD

**Issue by jmaffre** [docdoku/docdoku-plm#158]
Sometimes we need to know the type of a BinaryResource, and the name is not sufficient (e.g. scorm zip).

It could lead to unnecessary download when the binary resource is located in the cloud.

We should have a way to know the type of a binary resource _before_ physically getting it.

**Comment by mguimard** [comment]
Scorm support has been removed and the need to know sub-resources content length is not anymore a current concern. Please reopen if needed
