### ISSUE TITLE
[DMU] Relative position on Marker

### ISSUE THREAD

**Issue by TaylorHub** [docdoku/docdoku-plm#287]
When you put a marker in a part, and you move this part in the product assembly, the part keep the same absolute position.
The marker should have a position relative to the part it marks.

**Comment by mguimard** [comment]
Actually not a bug, it's working as expected, but the model should be completely reworked.
Markers must be handled in configuration (WIP, Baselines, Product instances) and indeed relative to the leaves.

**Comment by mguimard** [comment]
https://github.com/docdoku/docdoku-plm/issues/551
