### ISSUE TITLE
[ACL] Access to a ressource when the user hasn't ACL on it!

### ISSUE THREAD

**Issue by TaylorHub** [docdoku/docdoku-plm#297]
Now, when a document ( or part or product or change-item) has ACL and you add a new user to the workspace, the new user have any access to it. 
A solution can be to create a user-group "All" with all the new user.

**Comment by mguimard** [comment]
Actually not a bug, the new user  should not have access to protected entities.
The workspace administrator has to grant access on those entities to the new user.
