### ISSUE TITLE
Invalid permanent link redirection on IE11

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#312]
Only on IE 11
Select a document.
Click on its permanent link (on the right of the "eye" icon).
The application redirects us on application home page with "undefined" workspace selected (cf screenshot).
![snipimage](https://cloud.githubusercontent.com/assets/1931399/3147139/e54d52bc-ea52-11e3-84aa-426f45e74b93.JPG)

**Comment by mguimard** [comment]
Cannot still reproduce, tested on latest Windows 10 and Microsoft edge. Closing issue
