### ISSUE TITLE
Cancel drop action isn't implemented the same way on parts, documents and products

### ISSUE THREAD

**Issue by chadidas** [docdoku/docdoku-plm#356]
when we cancel delete action on documents, the  confirmation-box disappears nonetheless for parts, issues, baselines and part's templates another confirmation box appears.

**Comment by TaylorDocdoku** [comment]
Should be fix with 2814fd67538de5e647ea9e2f9935f0a434f629b4 and 14ed85de81832398db9be991410bb46aae05feb1

**Comment by mguimard** [comment]
Replaced native confirm boxes by our custom confirm box on every delete actions, closing the issue canno't see this anymore.

**Comment by TaylorDocdoku** [comment]
The problem still exist in ChangeManagement when constraint exists between item

**Comment by mguimard** [comment]
Not happening with constraints, to reproduce the bug : navigate to workflow list, then navigate to issues list, select all, click on delete button.
