### ISSUE TITLE
add workflow in template

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#372]
It should be possible to specify the workflow model to apply when instianting a document model or a part model.
It should be possible to mention if this attachment is mandatory or could be changed when creating the document or the part.

**Comment by TaylorDocdoku** [comment]
Server side is on feature-workflowInTemplate branch.
The template management was also extract from the document and the part management.

**Comment by mguimard** [comment]
closed since 20300c2e436cce49280602888fa117fece35a0b1
