### ISSUE TITLE
DPLM: notifications not translated

### ISSUE THREAD

**Issue by chadidas** [docdoku/docdoku-plm#377]

**Comment by mguimard** [comment]
Also, we should not allow the user to change the language in use in DPLM from the settings. Once connected we need to know its language, and then apply it.

**Comment by mguimard** [comment]
The accounts informations must be stored in user home directory (user name / language). in a .dplm file

**Comment by mguimard** [comment]
This has been implemented in bb168cc8fc2186650867491098cd767b190a47e0
