### ISSUE TITLE
Issue when user uses 'en' language

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#379]
Select 'en' language, the buttons don't appear well probably because of translation missing.

![capture du 2014-12-17 21 30 03](https://cloud.githubusercontent.com/assets/868602/5478625/247c8082-8636-11e4-901b-0bc0cb1c0db9.png)

**Comment by TaylorDocdoku** [comment]
Seems work in dev & public cloud

**Comment by florentgarin** [comment]
Did you change your local to en ?

Florent Garin (DocDoku)

**Comment by mguimard** [comment]
Was caused by untracked files non deleted when removing entry from gitignore : 8a110a9f81af3619399d95c0f1473fffc95b0511
