### ISSUE TITLE
Rest api behavior when non authenticated

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#384]
@florentgarin 
Since a recent commit, accessing the rest api without being authenticated redirects on the login page, shouldn't we have a 401 http code instead ?

**Comment by florentgarin** [comment]
Yes probably, for the rest api point of view that's better. But we should
hence make the redirection on the JavaScript layer so the user who uses our
web interface can easily reconnect.

Florent Garin (DocDoku)

**Comment by mguimard** [comment]
Closed by 3f5a6bdb9191c6c3aad0c957a11f2ec750792598

**Comment by florentgarin** [comment]
Still issue...

**Comment by mguimard** [comment]
Please describe the scenario, i can't reproduce.

**Comment by florentgarin** [comment]
When the timeout happen every ajax call get a 401 response (as expected)
but without redirecting the page to the logon one.

Florent Garin (DocDoku)

**Comment by mguimard** [comment]
Right, this wasn't implemented. Done now.
