### ISSUE TITLE
DPLM-CLI

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#388]
"dplm" command shows the command usage but not "dplm help". This could be disturbing.

**Comment by mguimard** [comment]
Currently we have : 

Command "dplm"    

    docdoku-plm/docdoku-cli$ ./dplm -h localhost -P 8080 -p bar -u foo
    
    usage: dplm <command> [<args>]
    DocDokuPLM command-line client, version 1.0.
    Type 'dplm help <command>' for help on a specific command.

    Available commands:
       checkin (ci)
       checkout (co)
       create (cr)
       get
       help (?, h)
       put
       status (stat, st)
       undocheckout (uco)

    For additional information, see http://www.docdokuplm.com

Command "dplm help"  

    docdoku-plm/docdoku-cli$ ./dplm -h localhost -P 8080 -p bar -u foo help
    Describe the usage of this program or its subcommands.
    
     <command>                  : the command to display the help information
     -F (--format) <format>     : output format, possible value : json
     -P (--port) <port>         : port number to use for connection; default is 80
     -h (--host) <host>         : host of the DocDokuPLM server to connect; default
                              is docdokuplm.net
     -p (--password) <password> : password to log in
     -u (--user) <user>         : user for login


What should be the output for the dplm help ?

**Comment by florentgarin** [comment]
The problem is dplm help doesn't list the available command.

2015-01-16 9:58 GMT+01:00 Morgan Guimard <notifications@github.com>:

> Currently we have :
>
> Command "dplm"
>
> docdoku-plm/docdoku-cli$ ./dplm -h localhost -P 8080 -p bar -u foo
>
> usage: dplm <command> [<args>]
> DocDokuPLM command-line client, version 1.0.
> Type 'dplm help <command>' for help on a specific command.
>
> Available commands:
>    checkin (ci)
>    checkout (co)
>    create (cr)
>    get
>    help (?, h)
>    put
>    status (stat, st)
>    undocheckout (uco)
>
> For additional information, see http://www.docdokuplm.com
>
> Command "dplm help"
>
> docdoku-plm/docdoku-cli$ ./dplm -h localhost -P 8080 -p bar -u foo help
> Describe the usage of this program or its subcommands.
>
>  <command>                  : the command to display the help information
>  -F (--format) <format>     : output format, possible value : json
>  -P (--port) <port>         : port number to use for connection; default is 80
>  -h (--host) <host>         : host of the DocDokuPLM server to connect; default
>                           is docdokuplm.net
>  -p (--password) <password> : password to log in
>  -u (--user) <user>         : user for login
>
> What should be the output for the dplm help ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/388#issuecomment-70225253>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner
