### ISSUE TITLE
[Template] Check documentId and partNumber on ServerSide

### ISSUE THREAD

**Issue by TaylorDocdoku** [docdoku/docdoku-plm#390]
When we create a new Part or a new Document the Id is check. 
We verify if the id match its template mask, but this verification is only do on ClientSide.
We should do it in ServerSide.

**Comment by florentgarin** [comment]
Right with the precision that the automatic number generation is not a
constraint to check it is just a client helper proposal. Only the mask
correctness has to be verified

Florent Garin (DocDoku)
Le 14 janv. 2015 12:02, "Taylor LABEJOF" <notifications@github.com> a écrit
:

**Comment by mguimard** [comment]
Closed by 7168712b5ad7779a983d653b1f8a9525be00c56b
