### ISSUE TITLE
translation missing

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#397]
The info message that suggests that task are missing inside an activity does not have a english translation.

**Comment by mguimard** [comment]
The translation appears to be correct, a recent commit on locale handling should have corrected a bug when changing language.

**Comment by florentgarin** [comment]
The problem came from the fact that WorkflowResource.assignRoleToTasks raise the exception.
This method should not perform any business checks but just makes its work which is preparing the data for the business layer (EJB).
