### ISSUE TITLE
[Template creation] mask without wildcard

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#408]
For documents and parts templates, the user can define a mask without '#' and '*' characters. Then the template cannot be used for creating more than one document.

We shouldn't let the user fill the mask without at least a wildcard character. Also check on server side. #390

**Comment by florentgarin** [comment]
Yes fundamentally you are right but I'm wondering if it's not over
engineering to implement such feature on the server side.
More it would be hard to maintain as the rules/pattern available can change.

At least, perhaps we could just provide a client side suggestion?

2015-01-29 14:35 GMT+01:00 Morgan Guimard <notifications@github.com>:

> For documents and parts templates, the user can define a mask without '#'
> and '*' characters. Then the template cannot be used for creating more than
> one document.
>
> We shouldn't let the user fill the mask without at least a wildcard
> character. Also check on server side. #390
> <https://github.com/docdoku/docdoku-plm/issues/390>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/408>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by mguimard** [comment]
Ok, i'll add this information on mask help.

**Comment by mguimard** [comment]
Closed by 7168712b5ad7779a983d653b1f8a9525be00c56b
