### ISSUE TITLE
[Translations] Locale.getDefault() not always necessary

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#416]
If you try to create an organisation that already exists, the server message is using the locale of the machine, not the user's one. This service is using Locale.getDefault(), but we can use the user language here.

There seems to be many other services where we use Locale.getDefault() whereas the user locale can be resolved.

**Comment by Hunsu** [comment]
I can't reproduce the bug for the organization creation. I checked the other  Locale.getDefault() calls and I didn't find any one that is unnecessary.

**Comment by mguimard** [comment]
https://github.com/polarsys/eplmp/commit/11b19f62e2bc1baa417358f56bb5b3dc7eff7929
