### ISSUE TITLE
[Edit Baseline Product]

### ISSUE THREAD

**Issue by JuLink** [docdoku/docdoku-plm#426]
At the baseline edition, changing the part version changes graphically the iteration but when the user save the edition, the iteration is still the old one.
Example:
- The baseline contain a part version B iteration 3
- Change the version to return to version A which only have 1 iteration
Visually the interface show Version A, Iteration 1 but when the user click on save, an error message appear "The part [...] revision "A" iteration "3" or its sub-elements have not been found"

**Comment by mguimard** [comment]
Closing the issue as we're leaving this functionality
