### ISSUE TITLE
[Language] Changing account

### ISSUE THREAD

**Issue by JuLink** [docdoku/docdoku-plm#429]
If the user is connected with an English account and then try to connect to a French account. The language will remain English. And vice versa.

**Comment by JuLink** [comment]
Remove local storage lang entry

**Comment by mguimard** [comment]
We could keep the local storage approach and use the technique described there : 
http://stackoverflow.com/questions/21256479/setting-requirejs-i18n-locale-dynamically

What is sure, is that we cannot make any http request before calling require.config which needs to know the current language to load the translation plugin.

Possible implementation : 

Change default 'en' to 'dummy', then when we really know the user language : compare it to local value, and decide whether to reload or not the page.
