### ISSUE TITLE
[Part and Baseline] Baseline with iteration not check-in

### ISSUE THREAD

**Issue by JuLink** [docdoku/docdoku-plm#431]
When the user create a baseline and try to modify it, iteration not checkin are shown in the list. This shouldn't be the case because an iteration can be cancelled and can cause an error.

- Check out a part A
- Create a baseline (a warning inform you that the baseline ignore the last iteration of part A)
- Edit the baseline and change the iteration of part A to use the last iteration
- Return to the Part section and try to "Undo Check out"

**Comment by mguimard** [comment]
This cannot happen anymore, since we're targeting last complete iteration, and not WIP ones.
