### ISSUE TITLE
[Document management] Add actions proposal on file download

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#437]
We should ask the user if he wants to checkout the document when he downloads a file on a documents which is not checkouted.

**Comment by florentgarin** [comment]
Not sure, that could be very annoying to be asked for that every time we
download a file.

2015-02-13 16:50 GMT+01:00 Morgan Guimard <notifications@github.com>:

> We should ask the user if he wants to checkout the document when he
> downloads a file on a documents which is not checkouted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/437>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by mguimard** [comment]
Right
