### ISSUE TITLE
"Config spec" label instead of "Baseline"

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#442]
Please modify the "Config spec" label in "Baseline"

**Comment by florentgarin** [comment]
Actually Config Spec is a more generic than Baseline as it includes
Baselines but Also EffectivityConfigSpec, Instances...

2015-02-16 13:25 GMT+01:00 ericdescargues <notifications@github.com>:

> Please modify the "Config spec" label in "Baseline"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/442>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by ericdescargues** [comment]
But "Config Spec" is not really understood by DM users : I think it will be a good thing to modify it at least in DM context...

**Comment by florentgarin** [comment]
Ok right for the DM part, we should find a better term.

**Comment by mguimard** [comment]
What about 'backup' / 'sauvegarde' for DM ?

**Comment by ericdescargues** [comment]
I think "Baseline" seems to be relevant for DM context too (already used
in engineering) but let the PO decide.

---
We help industrial organizations digitize their business

Cordialement / Regards,
*Eric Descargues*
Managing partner
*DocDoku* - http://www.docdoku.com
*Digital Enterprise Applications*
37 rue Lancefoc - 31000 Toulouse
Mobile : + 336 70 00 12 91 - Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner


2015-03-03 23:28 GMT+01:00 Morgan Guimard <notifications@github.com>:

**Comment by mguimard** [comment]
No more baseline in DM. A new feature replacing document baselines has been added, and is called Document collections. I can't see any 'Config spec' labels left in current dev branch. Please re open if needed.
