### ISSUE TITLE
[Product creation] Duplicate error message

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#445]
When the button "Create Product" is clicked multiple times, the same error message appears again and again. Should appear only once.

![screen shot 2015-02-16 at 17 01 34](https://cloud.githubusercontent.com/assets/644898/6215133/28c62cd6-b5fe-11e4-87b1-241a70a841f4.png)

**Comment by mguimard** [comment]
Nothing abnormal, if the user clicks 8 times on the button, we show 8 errors ! How can this be more "clear" ? The user can dismiss the error by clicking it, so, nothing seems abnormal to me.

**Comment by elisabelgenereux** [comment]
We shouldn't show the same error more than once

**Comment by mguimard** [comment]
Let's remove any error message on form re-submission.

**Comment by elisabelgenereux** [comment]
I would prefer keeping the error(s) and warning(s). Maybe we can twinkle the error.
