### ISSUE TITLE
[Custom Attributes] Ordered attributs list

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#451]

**Comment by florentgarin** [comment]
Back-end done on branch "feature-ordered-attributs".
What remains is front part: offer the possibility to order (move) attributs for Part model, document model, document and part and simply send the array is the proper order.

**Comment by florentgarin** [comment]
Attributes inside document and part with "frozen attributes" cannot be moved.

**Comment by mguimard** [comment]
closed by 24d44c691996ab1b03f539f54f781328eab14323
