### ISSUE TITLE
Error management in part assembly is missing 

### ISSUE THREAD

**Issue by chadidas** [docdoku/docdoku-plm#453]
When we create a new part  from the assembly screen, and the name of the part is empty or contain unothorzed characters we dont have any feedback that the creation failed.

**Comment by mguimard** [comment]
Right, moreover, the creation of new parts are done in the rest layer. This should be move into the business layer and raise an appropriate error if so.

**Comment by mguimard** [comment]
https://github.com/docdoku/docdoku-web-front/commit/198cac49d4ab34dd811f64c3990a713e7bd8ad26
