### ISSUE TITLE
[Product] mesage on product page

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#457]
When there is no part on a given workspace a message indicates that we cannot create a product for now (on product page).
Although that message is correct, we should probably wait for the user tents to create one to show him that message.

**Comment by mguimard** [comment]
Why should we wait ? We already know it will fail. Maybe it's a bit overkill, but at least the user is told.

**Comment by elisabelgenereux** [comment]
I agree with Morgan

**Comment by florentgarin** [comment]
Oky.
