### ISSUE TITLE
ACL: Strange behavior of redirection when we disabe group or user  

### ISSUE THREAD

**Issue by chadidas** [docdoku/docdoku-plm#466]
To reproduce the bug:

Create a milestone,  add an ACL that contains groups /users
disable your groups or/and users
Go back to the change management screen, you will be redirected to document management !! you cannot access to change management screen,
if we enable the disabled (groups/users)  then we can access to the change management screen,

**Comment by elisabelgenereux** [comment]
Note: the redirection goes now to the workspaces page

**Comment by mguimard** [comment]
Being in a group which is disabled restricts access to every module of the workspace. This is actually not a bug. Closing the issue.
