### ISSUE TITLE
[Document Management ] Advanced search needs to be checked

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#469]
If you want to search (via left menu under Tags) all the documents "SPEC%", if you put 'SP' in the ID no result, if you put 'SPEC' OK.
And Quick search is not case sensitive but advanced search yes

**Comment by mguimard** [comment]
Reproduced this week, submitting searches with 2 or 3 letters doesn't provide relevant results with elastic search, at least in the way we have configured it. Maybe some settings modification could solve the problem. Should we boost or search only in id and title fields if the user inputs less than 4 letters ?

**Comment by ericdescargues** [comment]
Today, what are the rules concerning search with elastic search and what
are the most common uses ?

---
We help industrial organizations digitize their business

Cordialement / Regards,
*Eric Descargues*
Managing partner
*DocDoku* - http://www.docdoku.com
*Digital Enterprise Applications*
37 rue Lancefoc - 31000 Toulouse
Mobile : + 336 70 00 12 91 - Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner


2015-03-03 23:20 GMT+01:00 Morgan Guimard <notifications@github.com>:
