### ISSUE TITLE
[Permalink] Error message

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#478]
Steps to reproduce:

1. Generate a private link for a document/part.
2. Logout
3. Go to the generated link
4. Clic on "See it on management"
5. Error instead of login page

**Comment by elisabelgenereux** [comment]
Same error when user session has expired

**Comment by mguimard** [comment]
Fixed by 8740b9e36327912a31d54964c4fffefa42efeb9c
