### ISSUE TITLE
[Product Deletion] Cannot destroy product associated with deliverable

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#480]
Steps to reproduce that bug:

1. Create a part
2. Create a product with this part as root part
3. Create a baseline from this product
4. Create a deliverable associated with these previously created product and baseline
5. Remove the baseline
6. Try to remove the product

![screen shot 2015-03-04 at 11 01 46](https://cloud.githubusercontent.com/assets/644898/6481456/f035c252-c25d-11e4-9b63-c96c04e22c9c.png)

Error on navigator console:

DELETE http://localhost:8989/api/workspaces/testEmptyList/products/TST-2 500 (javax.ejb.EJBException: Transaction aborted)

**Comment by florentgarin** [comment]
nothing abnormal, but the message should be more informal.

2015-03-04 11:04 GMT+01:00 Elisabel Genereux <notifications@github.com>:

> Steps to reproduce that bug:
>
>    1. Create a part
>    2. Create a product with this part as root part
>    3. Create a baseline from this product
>    4. Create a deliverable associated with these previously created
>    product and baseline
>    5. Remove the baseline
>    6. Try to remove the product
>
> [image: screen shot 2015-03-04 at 11 01 46]
> <https://cloud.githubusercontent.com/assets/644898/6481456/f035c252-c25d-11e4-9b63-c96c04e22c9c.png>
>
> Error on navigator console:
>
> DELETE http://localhost:8989/api/workspaces/testEmptyList/products/TST-2
> 500 (javax.ejb.EJBException: Transaction aborted)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/480>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by mguimard** [comment]
Moreover, shoudn't we have a generic error message (on unhandled errors)  instead of all this unreadable markup, and let the user report this error ?

**Comment by florentgarin** [comment]
I think so.
