### ISSUE TITLE
[Doc Search] Left menu selection

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#489]
When you start an advanced search from the Search item in the left vertical menu, the last selected item remains selected.

![screen shot 2015-03-04 at 10 05 34](https://cloud.githubusercontent.com/assets/644898/6480666/72021504-c256-11e4-9933-1824ef574ecc.png)

Moreover, the advanced search doesn't show any result.

**Comment by mguimard** [comment]
Selected item fixed. For the search results not displayed, we have an other opened issue.
