### ISSUE TITLE
[Iteration tab] Differences between part and document modal

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#511]
Keep the good parts from each ;)

To keep from the doc modal:
* Space between icon and text inside the buttons
* Position buttons just below the Revison note line

![screen shot 2015-03-12 at 16 38 44](https://cloud.githubusercontent.com/assets/644898/6621391/a4a2944e-c8d6-11e4-890e-d5a74cc17173.png)

To keep from the doc modal:
* Colors intensity

![screen shot 2015-03-12 at 16 36 58](https://cloud.githubusercontent.com/assets/644898/6621392/a4a40cd4-c8d6-11e4-8a64-176d11e03732.png)

To change for all:
* Align the buttons to the left of the input

**Comment by chadidas** [comment]
The template is the same for both

**Comment by elisabelgenereux** [comment]
Ooops... I had to run a grunt serve...

Remaining:
* Position buttons just below the Revison note line
* Colors intensity
* Align the buttons to the left of the input
