### ISSUE TITLE
[Delete document] Document linked to product instance data

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#556]
Deleting a document referenced in a product instance path data fails because of constraint. The link should be removed before trying to remove the document.

**Comment by mguimard** [comment]
We should not delete the link, but we should prevent the document deletion.

**Comment by florentgarin** [comment]
exactly. DocumentLink target now DocumentRevision and the constraint will apply and hence prevent the deletion. We should just insure a meaningful message is displayed to the user.
