### ISSUE TITLE
Can't login to localhost:4848

### ISSUE THREAD

**Issue by StevenIsaacs** [docdoku/docdoku-plm#572]
I was following the instructions on https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide and when I got to:

```
Glassfish Configuration

Start the glassfish server and log into the admin console http://localhost:4848.
```

I can't login. It's unclear as to what user name and password to use. Are these "docdokuplm_user@localhost" and "password" (from the MySQL configuration)? I've tried a number of combinations none of which work. I even tried the asadmin password to no avail. I'm stuck!

Thanks

**Comment by florentgarin** [comment]
It is not the mysql login/password it is the glassfish admin one. Most of
the time there even no password to fill to enter into the console.

You can try admin as the login and adminadmin as the password.

Florent Garin

**Comment by StevenIsaacs** [comment]
Thanks for the reply. Didn't work. I'll read the glassfish docs.

**Comment by StevenIsaacs** [comment]
I'm running glassfish in an lxc container. I can login using an ssh session to the container and then running asadmin. (the container is headless) I can also login using the lynx browser and the localhost:4848 URL. 

I can't login from outside the container using the container's IP address as part of the URL. In this case 10.0.3.253:4848

I must have unknowingly done something to lock this down when installing glassfish.
