### ISSUE TITLE
Build failure when building docdoku-server-web.

### ISSUE THREAD

**Issue by StevenIsaacs** [docdoku/docdoku-plm#573]
Using the command: `mvn compile` I'm seeing this error:
```
[INFO] Building docdoku-server-web Java EE 7 Webapp 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/docdoku/docdoku-common/2.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/docdoku/docdoku-common/2.0-SNAPSHOT/docdoku-common-2.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] docdoku-server-web Java EE 7 Webapp ............... FAILURE [2.412s]
[INFO] docdoku-server-ear Java EE 7 Assembly ............. SKIPPED
```

The URLs are returning 404. Here's what's there:
http://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/

**Comment by mguimard** [comment]
Hello,
Running the same command doesn't fail here, which version of maven are you using ?

**Comment by StevenIsaacs** [comment]
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-45-lowlatency", arch: "amd64", family: "unix"

**Comment by florentgarin** [comment]
Are you typing the mvn compile cmd inside the root folder?

2015-04-24 17:14 GMT+02:00 StevenIsaacs <notifications@github.com>:

> Apache Maven 3.0.5
> Maven home: /usr/share/maven
> Java version: 1.8.0_40, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-8-oracle/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "3.13.0-45-lowlatency", arch: "amd64", family:
> "unix"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/573#issuecomment-95962779>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner

**Comment by StevenIsaacs** [comment]
```
user@docdoku-plm:~/docdoku-plm$ pwd
/home/user/docdoku-plm
user@docdoku-plm:~/docdoku-plm$ ls
docdoku-android-client  docdoku-dplm         LICENSE.txt  README.md
docdoku-cli             docdoku-node-server  NOTICE.txt
docdoku-common          docdoku-server       pom.xml
user@docdoku-plm:~/docdoku-plm$ mvn compile -rf :docdoku-server-web
...snip
[INFO] Building docdoku-server-web Java EE 7 Webapp 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/docdoku/docdoku-common/2.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repository.ow2.org/nexus/content/repositories/snapshots/org/ow2/docdoku/docdoku-common/2.0-SNAPSHOT/docdoku-common-2.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] docdoku-server-web Java EE 7 Webapp ............... FAILURE [2.177s]
[INFO] docdoku-server-ear Java EE 7 Assembly ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
...snip
```
I think you're missing the point. The URLs 404 meaning the download files don't exist at that location on the server. Please explain why that would not be a problem. 

You mentioned this worked for you. Can you do the same and provide the output so I can compare? 

Thanks

**Comment by JuLink** [comment]
`mvn compile -rf :docdoku-server-web ` does'nt seems to work on my station either. I have got the same output as you, do but `mvn compile` does. 

Do you have the same error when you run `mvn compile` ?

**Comment by StevenIsaacs** [comment]
I get an error on docdoku-server-web when I run `mvn compile` which is what sent me down this path. I dug a little deeper and found a failed attempt to install (`node install.js`). I don't like experimenting with things like this as root so have been building as an ordinary user. So, in a container, I built as root to see if that was a factor. No change.

```
[INFO] docdoku-server-viewer-multimedia .................. SUCCESS [0.019s]
[INFO] docdoku-server-ejb Java EE 7 Core ................. SUCCESS [1:01.800s]
[INFO] docdoku-server-web Java EE 7 Webapp ............... FAILURE [45.709s]
[INFO] docdoku-server-ear Java EE 7 Assembly ............. SKIPPED
```

```
> phantomjs@1.9.16 install /home/user/docdoku-plm/docdoku-server/docdoku-server-web/yo/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by StevenIsaacs** [comment]
I'm not a maven user nor a node.js user. I'm running Ubuntu 14.04, which is debian base, in the container. I believe I've figured out what the problem is. 

On debian systems a program named "node" is installed in /usr/sbin. The node.js version of `node` is renamed `nodejs` and is located in /usr/bin. Even for a normal user (at least for this Ubuntu 14.04 lxc container) the PATH variable has `/usr/sbin` before `/usr/bin` which means the maven build runs node from `/usr/sbin`.

To work around this confusion I created a symlink in `/usr/bin` (node -> nodejs) then changed the PATH variable to search `/usr/bin` before searching `/usr/sbin`. Doing this got me to:
```
└── grunt-lib-phantomjs@0.4.0 (eventemitter2@0.4.14, semver@1.0.14, temporary@0.0.8, phantomjs@1.9.16)
sh: 1: bower: not found
sh: 1: grunt: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
```
As root I used npm to install grunt-bower-cli, bower and grunt-cli then got me to:
```
[INFO] docdoku-server-viewer-multimedia .................. SUCCESS [0.024s]
[INFO] docdoku-server-ejb Java EE 7 Core ................. SUCCESS [0.320s]
[INFO] docdoku-server-web Java EE 7 Webapp ............... SUCCESS [7:19.169s]
[INFO] docdoku-server-ear Java EE 7 Assembly ............. SUCCESS [3.957s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
