### ISSUE TITLE
[Used-by] Part modal

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#605]
Add in the tab "Used by" of the part modal the parts that use the current part as a component or as a substitute, juste before the product instances that contains the part. (Use services added in 7f5c8568f7210628d5fc93e45ab04c9dd9f95406)

**Comment by florentgarin** [comment]
Actually, the "used by" tab should as possible inform the user of which objects hold a reference to the part.
This tab should help the user who cannot successfully remove a part because of an integrity violation without knowing which one it is.

**Comment by JuLink** [comment]
done in branch feature-used-by-as-component-or-substitute
