### ISSUE TITLE
[export ZIP]

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#611]
Exported zip are corrupted when exported from product.
We should check all other zips as well.

**Comment by florentgarin** [comment]
Also only the "all" zip works properly (other than from product).

**Comment by mguimard** [comment]
Cannot reproduce the corrupted zip bug. Do you have some inputs to reproduce it ?
Both options should work well now.

**Comment by florentgarin** [comment]
I saw that it was flagged corrupted when using 7Zip on Windows. Perhaps
that was the case because the zip was empty.

2015-05-25 11:53 GMT+02:00 Morgan Guimard <notifications@github.com>:

> Cannot reproduce the corrupted zip bug. Do you have some inputs to
> reproduce it ?
> Both options should work well now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/611#issuecomment-105191240>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner

**Comment by mguimard** [comment]
Catched an error in logs, the code could produce duplicate zip entries. Must be investigated

Caused by: java.util.zip.ZipException: duplicate entry: partnumber/filename.pdf
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
	at com.docdoku.server.rest.writer.FileExportWriter.addToZipFile(FileExportWriter.java:151)
