### ISSUE TITLE
[File on Part]

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#617]
We should be able to add file (other than CAD) on Part iteration.
Already done on model, need to add it on the service layer (on the same schema than for other objects).

**Comment by mguimard** [comment]
Almost done in a local branch, I will push it tomorrow on the remote.

**Comment by mguimard** [comment]
The branch https://github.com/docdoku/docdoku-plm/tree/feature-parts-attached-files contains some GUI and some server code to handle those files. Some wording is necessary as it is called "material files", but the idea is the same. The files must be uploaded in a subfolder named "attachedfiles", the user cannot choose the directory to upload them.
