### ISSUE TITLE
[PathToPathLink] Refresh list

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#628]
When creating a new link in a deliverable structure, the link type select should be updated.

**Comment by elisabelgenereux** [comment]
I think this is not possible to create a new typed link in a deliverable structure...

**Comment by florentgarin** [comment]
exactly it is part of the product definition hence it's created on the
product and tranferted to deliverable when rebased.

2015-06-05 16:23 GMT+02:00 Elisabel Genereux <notifications@github.com>:

> I think this is not possible to create a new typed link in a deliverable
> structure...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/628#issuecomment-109308451>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner
