### ISSUE TITLE
Cyrillic symbols converts to ????

### ISSUE THREAD

**Issue by bamps** [docdoku/docdoku-plm#640]
Hello!
I create new document with id АБВГ.100200.001.
After opening checked out tab it becames ????.100200.001

I'm using cloud https://www.docdokuplm.net with demo/demo login / pass.

**Comment by mguimard** [comment]
Hello, seems to be a server configuration issue, we'll investigate this problem.

**Comment by mguimard** [comment]
Fixed by 56410c50c56c593a2c27f3ff32715de263656017
