### ISSUE TITLE
[Upload ZIP/SCORM file] Upload ZIP/SCORM file doesn't work

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#645]
![unnamed](https://cloud.githubusercontent.com/assets/1931399/7982852/c5548e2e-0aba-11e5-82d7-876b125d1422.png)

**Comment by mguimard** [comment]
This cannot be reproduced, seems to be that google api was unreachable or has an unhandled error at the time this service was called.
