### ISSUE TITLE
[ElasticSearch] Redesign schema

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#647]
Currently, we're indexing iterations. However, requesting for single revisions isn't possible. As we only request for PartRevisions or DocumentRevisions, we need to change the way we index the entities.

For example, we could store data like this : 

    {
        "partNumber" : "...",
        "version": "A",
        iterations:[/*array of iterations containing currently stored data*/]
    }

**Comment by elisabelgenereux** [comment]
#469
