### ISSUE TITLE
[Switching 3D mode view]

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#667]
When switching from "Fly", "Track", "Orbit" mode the model disappears.

**Comment by mguimard** [comment]
Switching between these modes makes the camera reset, then you look somewhere else, and so, it naturally disappears. 

It doesn't disappear in some cases, precisely when your data is in the center of the scene. (All modes default camera's target is the scene origin)

What we can do is to keep the target and the camera position when switching modes.
