### ISSUE TITLE
[Typed link] Creation modal

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#670]
Only show one Save button as usual at the bottom right of the modal view.
Thus the save requests are only sent once, on Save button click

![screen shot 2015-06-16 at 15 30 59](https://cloud.githubusercontent.com/assets/644898/8184069/b638be98-143c-11e5-9185-107eee69f8bc.png)

**Comment by elisabelgenereux** [comment]
What should be the behavior for delete?

**Comment by florentgarin** [comment]
Perhaps a better feedback that the action is destructive, it is easy to click on the cross, what do you think?
