### ISSUE TITLE
[Organization] User (not creator of orga) does not see the organization he belongs to 

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#676]
![screen shot 2015-06-18 at 10 18 40](https://cloud.githubusercontent.com/assets/644898/8227078/6a345cfa-15a4-11e5-9350-61dcc8d652ee.png)

**Comment by florentgarin** [comment]
He cannot manage his organization but through his account page he can see
his organization.

2015-06-18 10:27 GMT+02:00 Elisabel Genereux <notifications@github.com>:

> [image: screen shot 2015-06-18 at 10 18 40]
> <https://cloud.githubusercontent.com/assets/644898/8227078/6a345cfa-15a4-11e5-9350-61dcc8d652ee.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/676>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner
