### ISSUE TITLE
[DPLM] dplm and wsdl doesn't match (www.docdokuplm.net) 

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#680]
![dplm](https://cloud.githubusercontent.com/assets/1931399/8251082/cd8be112-1679-11e5-8079-a96617eb20f7.png)

**Comment by mguimard** [comment]
This means that you're using an old version of the DPLM. Please download the latest one from docdokuplm.net.

We need to find a way to handle this gracefully.

**Comment by ericdescargues** [comment]
No, I have downloaded the latest DPLM client on docdokuplm.net

---
We help industrial organizations digitize their business

Cordialement / Regards,
*Eric Descargues*
Managing partner
*DocDoku* - http://www.docdoku.com
*Digital Enterprise Applications*
37 rue Lancefoc - 31000 Toulouse
Mobile : + 336 70 00 12 91 - Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner


2015-06-19 12:09 GMT+02:00 Morgan Guimard <notifications@github.com>:

**Comment by mguimard** [comment]
Will be available on next deployment. 
Closed by 795387d676ec123e9a7f1fb6fd55c95e5d866265
