### ISSUE TITLE
[Typed Link] Substitute link

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#691]
The UI does not permit to define typed linked which involve substitute link.

**Comment by mguimard** [comment]
Closed by 19a8a21bffd461389258623509103b693f4ed110

**Comment by elisabelgenereux** [comment]
Enhancements:

* remove "SHOW SUBSTITUTES" button, always show substitutes on product structure

* standardize information texts ("Has substitutes" VS "substitute part")
