### ISSUE TITLE
[getLastCheckedInIteration] method

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#694]
getLastCheckedInIteration implementation navigates backward the revision (part or document) which could be an unexpected behavior and error prone.
As an example issue #693 was probably made because of that.

We should either verify if we really need to navigate backward revision or rename the method.

**Comment by mguimard** [comment]
Which are the cases where we need to navigate backward revisions ?

**Comment by florentgarin** [comment]
I think we don't need to navigate backward, but we have to be sure ;-)
