### ISSUE TITLE
[Firefox] Assembly

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#697]
The unity select is broken, seems to be a basic input field...

![screen shot 2015-06-30 at 10 02 57](https://cloud.githubusercontent.com/assets/644898/8426329/3b0f5ece-1f0f-11e5-8405-297aeb3dd92e.png)

**Comment by mguimard** [comment]
We should use a cross platform library such as http://brianreavis.github.io/selectize.js/
