### ISSUE TITLE
[QueryBuilder] Empty search

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#719]
When searching without filling any field, the part list is reset and shows a blank table. We should prevent this behavior.

**Comment by elisabelgenereux** [comment]
still see that bug

![screen shot 2015-07-03 at 10 10 58](https://cloud.githubusercontent.com/assets/644898/8495201/dfb1530c-216b-11e5-8dca-736648191eee.png)

**Comment by mguimard** [comment]
Please provide a screenshot of all the page

**Comment by elisabelgenereux** [comment]
No pb, here it is (but the empty list appears at any time for me)

![screen shot 2015-07-03 at 14 06 58](https://cloud.githubusercontent.com/assets/644898/8498916/0644e88c-218d-11e5-95f5-347af10f9b7b.png)
