### ISSUE TITLE
[PathData] Open twice the modal

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#720]
Clicking on the asterix icon from the product structure opens twice the modal

**Comment by elisabelgenereux** [comment]
cannot reproduce

**Comment by mguimard** [comment]
If this can help, here are two screenshots
![pathdata-1](https://cloud.githubusercontent.com/assets/3205135/8473444/061f2c52-20aa-11e5-89d5-80718d6dc98e.png)

![pathdata-2](https://cloud.githubusercontent.com/assets/3205135/8473448/0d11cf4c-20aa-11e5-8d42-af38be0da279.png)

**Comment by elisabelgenereux** [comment]
seems to open a creation modal and an edition modal... (You have the iteration indicator only once)

**Comment by mguimard** [comment]
Yes I saw it, and also, the paths are not the same : root path for the creation modal, and the right path for edition modal. This should be covered by E2E tests once resolved.
