### ISSUE TITLE
[Count] Changes Management

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#726]
Show count on every item of contextual left menu

![screen shot 2015-07-02 at 11 49 57](https://cloud.githubusercontent.com/assets/644898/8474460/7d73b920-20b0-11e5-88e3-4be9dce0d6fc.png)

Exhaustive list:
- workflows
- milestones
- issues
- requests
- orders

**Comment by florentgarin** [comment]
Not sûre it's valuable, especially for workflows and milestones.

Florent Garin (DocDoku)
Le 2 juil. 2015 11:50, "Elisabel Genereux" <notifications@github.com> a
écrit :
