### ISSUE TITLE
[Workflow] Duplicated workflow can't be deleted

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#729]
After  duplication of a workflow, it can't be deleted (it seems to be deleted on HMI but when you come back on the list is always present)

**Comment by mguimard** [comment]
Cannot reproduce. Tests added.

Please provide a screenshot of the workflow

**Comment by ericdescargues** [comment]
"Validation specification struc22ture" is the duplicated workflow.

![bug-wfl](https://cloud.githubusercontent.com/assets/1931399/8572207/746cd30e-258b-11e5-854e-cf5b414b1117.jpg)

**Comment by mguimard** [comment]
The duplication is not the problem. This is due to a constraint : the workflow is in use in a document template. The "delete workflow" service should check whether it's used or not in a template a raise an error to the client.
