### ISSUE TITLE
[User defined function] Simplify GUI

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#735]
The GUI is quite complex to use and is made for geeks. We should remove the need to write the JS function.

Also we should show the amount of visited nodes.

**Comment by mguimard** [comment]
2438c33576ba30c287af66fdae8d591941769147

**Comment by elisabelgenereux** [comment]
1. Remove the Run button if no calculation has been added

2. Maybe we should display the Result with a different color or next to the calculation line to make it more visible
![screen shot 2015-07-09 at 11 27 21](https://cloud.githubusercontent.com/assets/644898/8592172/7dbf60be-262d-11e5-85e7-9196e7338617.png)
