### ISSUE TITLE
[Product Baseline] Unique names

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#747]
Currently, you can create two baselines on the same product, with the same name. This shouldn't be allowed.

**Comment by florentgarin** [comment]
right but not really an issue no ? It's up to the user to do what he wants.

2015-07-16 16:45 GMT+02:00 Morgan Guimard <notifications@github.com>:

> Currently, you can create two baselines on the same product, with the same
> name. This shouldn't be allowed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/747>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner

**Comment by mguimard** [comment]
Right, but there seems to be no way to distinguish them

**Comment by kelto** [comment]
And only the client check for a non empty name, no validation from the server.
