### ISSUE TITLE
[ProductInstance list] iteration number not updated on rebase

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#754]
When a user rebase a product instance, the modal is updated but not the list. We should update the list to display the right number of iterations.

**Comment by mguimard** [comment]
Cannot anymore since https://github.com/docdoku/docdoku-plm/commit/55a157b598cb1b5bb4cd4f767e779d3ec7a57cab

**Comment by kelto** [comment]
can since 4029af06612502f6ee0d40729f8e328897167bba

**Comment by mguimard** [comment]
Nice, an other thing : when switching between iterations, we are redirected on the first tab, it's a bit annoying

**Comment by kelto** [comment]
fixed since 46f930c206c23ef0d19c940b705c7a5837108647
