### ISSUE TITLE
[deliverable data]

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#789]
It's not possible to delete a deliverable data.
Should it be?

**Comment by elisabelgenereux** [comment]
Yes, it should be possible. From the product instance modal:

![screen shot 2015-08-13 at 17 43 16](https://cloud.githubusercontent.com/assets/644898/9254249/cad7629a-41e2-11e5-8f7c-b46edbbbf62a.png)

**Comment by mguimard** [comment]
The service already exists be seems to be unused (ProductInstancesResource.java:409)
