### ISSUE TITLE
[Part permalink] Assembly tab bug

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#814]
Must be an assembly part.

The page tries to load a 3D view but you get that error from the WS:

GET http://localhost:8989/api/workspaces/TestSampleLoader/parts/99273-A/instances 500 (Internal Server Error)

Unhandled system error : java.util.ArrayList$Itr.next threw java.util.NoSuchElementException in ArrayList.java at line 854

![screen shot 2015-08-28 at 15 10 23](https://cloud.githubusercontent.com/assets/644898/9546941/f0cc5dce-4d96-11e5-83ac-70423a1b8952.png)

**Comment by mguimard** [comment]
Please provide a scenario to reproduce.
