### ISSUE TITLE
[Date picker on Firefox]

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#820]
Unfortunately Firefox still doesn't support native date picker. Why not add polyfill so all dates could be easily entered?

**Comment by elisabelgenereux** [comment]
branch hotfix-datepicker

Style missing/broken:

* chosen date should appear with a blue background
* days out of month should appear grey (still not disabled)
* today date could appear with a specific background
* support "fr" localization
* "cursor: pointer" on each day case

**Comment by kelto** [comment]
When selecting a date attribute on the query builder, the input is a text input, no information on the date format is given to the user.
An exception is thrown when the server try to parse the date, which is not catch
