### ISSUE TITLE
[Workspace Dashboard] Js error on console

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#827]
Error: Invalid value for <path> attribute d="MZ"

![screen shot 2015-10-02 at 10 05 25](https://cloud.githubusercontent.com/assets/644898/10241918/3bbc4530-68ed-11e5-99ba-fd3bb8aa4945.png)

**Comment by mguimard** [comment]
should be closed with 9152bdf6d0ef6439884e808ef1297c578f49161c
