### ISSUE TITLE
[revision note]

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#833]
The popup suggesting no revision note has been filed is wrongly displayed.

**Comment by kelto** [comment]
Would that be a good behaviour ?
If one part/document or more does not have a revision note, then the prompt should appear. The revision note given by the user should only be applied on the item without a revision note.

**Comment by florentgarin** [comment]
2015-11-02 18:50 GMT+01:00 kelto <notifications@github.com>:

> Would that be a good behaviour ?
> If one part/document or more does not have a revision note, then the
> prompt should appear.
>
Yes and only if. That was the behavior before that regression.

> The revision note given by the user should only be applied on the item
> without a revision note.
>
As a consequence of the first sentence.
