### ISSUE TITLE
[File upload] Error must explain why file cannot be uploaded

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#834]
instead of just displaying "Bad request"

![screen shot 2015-10-30 at 10 07 44](https://cloud.githubusercontent.com/assets/644898/10841946/1808194a-7eee-11e5-9ac2-d04af1aabc64.png)

**Comment by mguimard** [comment]
closed by cd430a853407f26cc4dc07b87c121238facd83e5
