### ISSUE TITLE
[Login] UTF-8 character in login

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#838]
At the moment, we allow user to use any unicode character in the login. This is not entirely supported by the project, and cause strange behaviour.
We should either support this feature or normalize the login with [Normalizer](http://docs.oracle.com/javase/6/docs/api/java/text/Normalizer.html)

**Comment by mguimard** [comment]
This is related to the database encoding and charset. Consider using utf8_unicode_ci or utf8_general_ci
