### ISSUE TITLE
[Part Access] Can't access part checkout by another user

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#839]
If a part is checkout by another user, the user defined function can not be executed. Moreover the part modal can not be opened on that part from the pbs.

**Comment by florentgarin** [comment]
We have a design decision to make to determine if we allow the navigation
to follow up by selecting the previous iteration (only for LATEST config
spec).
Moreover we need also to decide which icon to display when a part is
checked out and we selected a baseline config spec.

2015-11-04 11:18 GMT+01:00 kelto <notifications@github.com>:

> If a part is checkout by another user, the user defined function can not
> be executed. Moreover the part modal can not be opened on that part from
> the pbs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/839>.
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner

**Comment by mguimard** [comment]
In my opinion, the navigation should be done with the "Latest checked in" filter which will resolve the problem. The problem Will still exists if a part is checked out A-1 (freshly created and not checked in). Moreover the user should be able to select the filter to use (if not already done)

We shouldn't give access to the checked out iteration to an other user. If an ACL prevents to access the data, the user should be well informed. 

So, to me, it's not really a bug. But we need too show a message explaining clearly  why he can't run the function.

**Comment by florentgarin** [comment]
Yes I know it is not really a bug but when trying to open the detail part
popup from the tree structure (not the part list) the screen goes dark and
an error appear on the js console.


2015-11-18 11:37 GMT+01:00 Morgan Guimard <notifications@github.com>:

> In my opinion, the navigation should be done with the "Latest checked in"
> filter which will resolve the problem. The problem Will still exists if a
> part is checked out A-1 (freshly created and not checked in). Moreover the
> user should be able to select the filter to use (if not already done)
>
> We shouldn't give access to the checked out iteration to an other user. If
> an ACL prevents to access the data, the user should be well informed.
>
> So, to me, it's not really a bug. But we need too show a message
> explaining clearly why he can't run the function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/839#issuecomment-157674498>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards winner

**Comment by mguimard** [comment]
I was answering the first part of the question. I will look at the second part of the issue. I thought opening the modal on a checked out part would open it on the previous iteration, no ?
