### ISSUE TITLE
[CADConverter] interface

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#844]
Question: Why the reason of supplying a tempDir?

ConversionResult convert(PartIteration partToConvert, BinaryResource cadFile, File tempDir)

I cannot why it is the responsability of the caller to give such temp folder.

**Comment by mguimard** [comment]
We're giving each converter a temporary space to make the conversion stuff. This temp dir is created by ConverterBean which will reuse this directory (read converted file and generate LODS) once the conversion is done. An other solution could be implemented if this is not desirable.

**Comment by florentgarin** [comment]
Oky but there is no need to enforce the both ConverterBean and the converter plugin to use the same temp dir.
ConverterBean gets the converted file from ConversionResult object.
I think it is always better to define thin interfaces.

**Comment by mguimard** [comment]
Closing this issue since olivbour's work has been merged.
