### ISSUE TITLE
[Markers] Created but not displayed

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#848]
In a few products, the markers are not displayed

For example, go to the "shop" workspace (user "demo") and visualize any one of the listed product. You won't be able to see any added marker there. Those products all use the same CAD file ("bunny2.obj")

**Comment by mguimard** [comment]
Actually the marker is larger than the model, I think your camera was inside the marker and you were not able to see it. It works as expected.
