### ISSUE TITLE
[Streams] Too many open files

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#851]
Seems to be some unclosed streams, needs to be checked and closed

**Comment by florentgarin** [comment]
lsof -u glassfish could help determining the leaking operation

**Comment by florentgarin** [comment]
Already see that elasticsearch client is not 100% guaranteed to be closed.

**Comment by florentgarin** [comment]
@kelto still need to wrap elasticsearch under singleton

**Comment by kelto** [comment]
Done since 50f3ae0d
I think we can close this issue.

**Comment by mguimard** [comment]
Our monitoring job show that it's stabilized, but there is still a very few more files opened on each check.
