### ISSUE TITLE
[PDF converter] connection impossible

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#852]
The converter works well but there is an issue when the app server restarts but a soffice process is still running. At that time the singleton cannot be initialized and hence no conversion is possible.
We should find a way to detect such case.

**Comment by kelto** [comment]
I don't see any "good" way to detect this. JodConverter offer an helper class, wrapping the [sigar](https://github.com/hyperic/sigar) library.
This library offer some bridge to system information and command (ps, top, kill, etc ...) on all system (unix,linux, windows, etc ...).
We could on the post-construction of the singleton, try to find the office process, and kill it.

**Comment by florentgarin** [comment]
OfficeManager.isRunning() is not sufficient?

**Comment by mguimard** [comment]
No it's not sufficient. After `officeManager.stop();` `running` is set to `false` . 

      $ ps -ef | grep office
      morgan    3900  3404  0 11:52 ?        00:00:00 /opt/openoffice.org3/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100;urp; -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100 -headless -nocrashreport -nodefault -nofirststartwizard -nolockcheck -nologo -norestore
      morgan    3902  3900  0 11:52 ?        00:00:00 [soffice.bin] <defunct>
      morgan    7029  5550  0 12:30 pts/3    00:00:00 grep --color=auto office

      // officeManager.stop();
      // officeManager.running == false

      $ ps -ef | grep office
      morgan    7040  5550  0 12:30 pts/3    00:00:00 grep --color=auto office

**Comment by mguimard** [comment]
Ran many tests with LibreOffice 5.3.2.2 and payara 181 with an heavy load. I wasn't able to reproduce the issue. I think we can close the issue. Please re-open if needed
