### ISSUE TITLE
[Template] Misleading name for attributes

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#860]
For both Document and Part, the creation date is changed when the template is updated. 
Should either change the name to modification date, create a new attribute modification date, or stop setting a date on the template update.

The same for the author, the behaviour is set for the modification author, not for the original author.

**Comment by kelto** [comment]
Should we display the modification date on the template modal or the template list view ?

**Comment by florentgarin** [comment]
On both? We have the place to do so.
