### ISSUE TITLE
[Glassfish 4.1.1] Unable to access document/part/change management modules

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#867]
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.persistence.jaxb.BeanValidationHelper

http://stackoverflow.com/questions/33319659/moxy-exceptions-in-javaee-jersey-2-0-project

**Comment by elisabelgenereux** [comment]
#895 should fix this issue

**Comment by kelto** [comment]
Payara does fix the problem. Discussion on whether to switch to payara or not should be discussed in issue 895.
