### ISSUE TITLE
[CAD file upload] Error alert appears while no error

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#869]
Steps to reproduce:
1. Open a part modal.
2. Go to the Files tab
3. Part must already have a CAD file uploaded
4. Remove the CAS file and upload a new CAD file
5. Save
6. The following alert appears:
   ![screen shot 2015-12-15 at 17 53 52](https://cloud.githubusercontent.com/assets/644898/11817353/d4c03b8c-a354-11e5-82a0-e43f2b89e069.png)

**Comment by mguimard** [comment]
To be reproduced

**Comment by mguimard** [comment]
This has been fixed
