### ISSUE TITLE
[File upload] Error when forbidden characters used for filename

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#873]
Show the list of the forbidden characters to help the user correcting his filename

FORBIDDEN_CHARS_FILE = {
            '/', '\', ':', '*', '?','"', '<', '>', '|', '~', '#',
            '^', '%', '{', '}','&','$','+',',', ';', '@', '\'', '`','=', '[', ']'
}

**Comment by mguimard** [comment]
Many issues related to this one. Closing issue
