### ISSUE TITLE
[Document templates list] List refresh

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#877]
Steps to reproduce:

You need a document template with files
1. Open its modal
2. Go to the Files tab
3. Remove all the files
4. Save

The document template still appears with files in the list:

![screen shot 2015-12-17 at 15 42 07](https://cloud.githubusercontent.com/assets/644898/11872334/fe4966e6-a4d4-11e5-99c9-d893da9d3fc0.png)

**Comment by kelto** [comment]
Seems to be present in all modal, the model.fetch called when the form is submitted does not take into account the asynchronous property of deleteFilesToDelete.
It might be working in other modal, but only because of the longer process it takes to perform the form submit client side.

**Comment by defmsy** [comment]
Solved by [this commit](https://github.com/docdoku/docdoku-web-front/commit/a5bb698024c394f13d2603e18741fec9542ab48a)
