### ISSUE TITLE
[CAD file upload] Filename not updated

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#879]
Steps to reproduce:

1. Open a part modal
2. Upload a CAD file
3. Do not save
4. Upload another CAD file

-> The filename has not been updated

Only interface bug: the right filename and file are saved.

**Comment by mguimard** [comment]
Cannot reproduce, maybe a special scenario ?

**Comment by elisabelgenereux** [comment]
Seems to be fixed...
