### ISSUE TITLE
[PDF Generator] Not working with xls files generated by query builder

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#882]

**Comment by mguimard** [comment]
What I tried : 

 - Generate a xls file from query builder (file is ok, data inside)
 - uploaded it to a new document
 - opened the document permalink
 - Pdf is generated and well displayed

Please provide a way to reproduce it

**Comment by elisabelgenereux** [comment]
Did you try with both Chrome and Firefox?

**Comment by mguimard** [comment]
I did

**Comment by elisabelgenereux** [comment]
Try using OpenOffice instead LibreOffice ;)

**Comment by mguimard** [comment]
Works with latest open office, and libreoffice.
