### ISSUE TITLE
[PartPermalink] Can not get a pdf preview on attached file

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#888]
The web services does not try to convert the pdf, and send the unconverted file with the pdf extension.

**Comment by florentgarin** [comment]
Fixed but with regression.
When downloading the attached file (not from the viewer which wants to convert it) it fails because output query param is not specified.

public Response downloadPartFile(@Context Request request,
                                     @HeaderParam("Range") String range,
                                     @HeaderParam("Referer") String referer,
                                     @PathParam("workspaceId") final String workspaceId,
                                     @PathParam("partNumber") final String partNumber,
                                     @PathParam("version") final String version,
                                     @PathParam("iteration") final int iteration,
                                     @PathParam("subType") final String subType,
                                     @PathParam("fileName") final String fileName,
                                     @QueryParam("type") String type,
                                     @QueryParam("output") String output,
                                     @PathParam("uuid") final String pUuid)
