### ISSUE TITLE
[Firefox] Permalink - pdf preview

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#893]
Seems that you cannot preview multiple files at the same time with Firefox. This browser only enables to preview the last file.

And each time you open a part permalink with attached files, Firefox suggests you to open an "empty.pdf" file...

![screen shot 2016-01-07 at 10 50 20](https://cloud.githubusercontent.com/assets/644898/12167447/7c34471c-b52c-11e5-873f-08c2bd35891f.png)
![screen shot 2016-01-07 at 10 47 44](https://cloud.githubusercontent.com/assets/644898/12167375/1b43a22c-b52c-11e5-85b8-4946266501b4.png)

**Comment by elisabelgenereux** [comment]
Scenario:
1. Create a part/document
2. Add multiple text files (.doc, .txt, .xls...)
3. Open the permalink
4. Go to Attached files tab
4. Try to open each pdf preview

**Comment by mguimard** [comment]
The message can be fixed here, it's a server configuration. The response header for "empty.pdf" are missing the content type.

Expected :

    Accept-Ranges: bytes
    Cache-Control: max-age=604800
    Connection: keep-alive
    Content-Length: 1058
    Content-Type: application/pdf
    Date: Thu, 07 Jan 2016 11:10:00 GMT
    Expires: Thu, 14 Jan 2016 11:10:00 GMT
    Keep-Alive: timeout=15
    Last-Modified: Mon, 04 Jan 2016 02:18:40 GMT
    Server: nginx
    ngpass_ngstatic: 1

Our configuration response headers :

    Accept-Ranges: bytes
    Cache-Control: public, max-age=0
    Connection: keep-alive
    Date: Thu, 07 Jan 2016 11:10:55 GMT
    Etag: "1058-1451873920000"
    Last-Modified: Mon, 04 Jan 2016 02:18:40 GMT
    Server: nginx/1.6.2 (Ubuntu)
