### ISSUE TITLE
[Glassfish] Switch on Payara

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#895]
http://www.payara.fish/

**Comment by kelto** [comment]
Should we set, in the user guide,  payara as the default server for the 2.5 ?

**Comment by florentgarin** [comment]
Yes Payara is the default server for the 2.5 version.

2016-03-21 12:16 GMT+01:00 charles <notifications@github.com>:

> Should we set, in the user guide, payara as the default server for the 2.5
> ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/895#issuecomment-199229917>
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - Award Winning platform for the
industry

**Comment by kelto** [comment]
Closing issue
