### ISSUE TITLE
[Product structure] Duplicate typed links

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#899]
Scenario: 
1. Create a product, its root part is an assembly of 2 other parts
2. Create a typed link between the 2 subparts
3. Create a new version of the root part
-> PBS displays the typed link twice in tree

**Comment by elisabelgenereux** [comment]
![doublon](https://cloud.githubusercontent.com/assets/644898/12238547/c7a1a7fc-b884-11e5-8aa0-de9bf397c08c.png)

**Comment by florentgarin** [comment]
There should also have the same issue when creating the baseline from such
state: the typed should probably be duplicated.

2016-01-11 17:00 GMT+01:00 Elisabel Genereux <notifications@github.com>:

> [image: doublon]
> <https://cloud.githubusercontent.com/assets/644898/12238547/c7a1a7fc-b884-11e5-8aa0-de9bf397c08c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docdoku/docdoku-plm/issues/899#issuecomment-170596300>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - Award Winning platform for the
industry

**Comment by elisabelgenereux** [comment]
No problem on baseline creation
