### ISSUE TITLE
[ACL] Global read only, part full access can not checkout

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#908]
A user having global read access but a full access on a part can not checkout this part.

Moreover there is no error handling on this use case:
![notif](https://cloud.githubusercontent.com/assets/3585948/12558194/b5ffb3ee-c38e-11e5-80b6-13799c25b026.png)

**Comment by kelto** [comment]
This bug might be present in a lot of place, since the used of ProductManagerBean.            return userManager.checkWorkspaceWriteAccess is widely used.

**Comment by florentgarin** [comment]
No the previous behavior was as expected please revert.

**Comment by florentgarin** [comment]
I think that could be closed, just confirm it.

**Comment by kelto** [comment]
yes, closing issue.
