### ISSUE TITLE
[Date management] client side

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#912]
date.js must be fixed
The variable offset must depend on the date we manipulate not on now date...
We should only use correctFormatTimestamp function and remove formatTimestamp function

**Comment by mguimard** [comment]
Many modification and simplifications made.
Also updated momentjs to latest version.

https://github.com/docdoku/docdoku-web-front/commit/ed8e3b5cfd93e021ca13b877d479694204bde7a0
