### ISSUE TITLE
[Refactor] ejb

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#916]
Following methods implemented in DocumentManagerBean should be in UserManagerBean instead:

- public User savePersonalInfo(String pWorkspaceId, String pName, String pEmail, String pLanguage)
- public User[] getUsers(String pWorkspaceId)
- public User[] getReachableUsers(String workspaceId)

**Comment by kelto** [comment]
savePersonalInfo does not seems to be used anywhere and should be deleted.
