### ISSUE TITLE
[Organization pages] Display error messages when user is not admin

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#918]
The user should not be able to see those pages if he administrates no organization or if the provided organization is null:
- accountAddingForm.xhtml
- organizationEditionForm.xhtml

The page manageAccounts.xhtml could redirect to organizationMenu.xhtml instead of showing an error page.

**Comment by mguimard** [comment]
Not sure that we still have this issue since JSF pages has been removed. Should be checked.

**Comment by defmsy** [comment]
It may be interesting to add a method to check if user is admin of his organization to the rest api?
This method would allow then to customize the ui based on organisation admin rights.

**Comment by mguimard** [comment]
If that doesn't lead to security issues we could also add the organization's admin login to the OrganizationDTO class to avoid a second API call

**Comment by defmsy** [comment]
It seems to be a better solution. I don't think that provide the admin login would lead to security issue.

**Comment by defmsy** [comment]
[This commit](https://github.com/docdoku/docdoku-web-front/commit/2a2b9140b24e882b8b77d1d75b82e7734d74cceb) has improved organization-management section. Not owner users can't see or access unauthorized pages, buttons or inputs. Maybe error messages are not necessary anymore?
