### ISSUE TITLE
[ACL] add ACL when only one user in workspace

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#920]
When the administrator tries to save ACL on a document (maybe a part as well or another item), he gets the following js error:

acl-checker.js:37 Uncaught TypeError: Cannot read property 'length' of undefined

![screen shot 2016-02-05 at 17 27 19](https://cloud.githubusercontent.com/assets/644898/12852157/e456f6d8-cc2d-11e5-9297-1601bed6992b.png)

**Comment by florentgarin** [comment]
What do you mean by "administrator"?
workspace administrator or superuser?

**Comment by kelto** [comment]
The workspace administrator.

**Comment by mfrederic** [comment]
Closed by commit 168c4fd6eed8591b31ddfb5f7a2cb273f02aa035.
The getWorkspaceSpecificUserGroupMemberShips() method of WorkspaceMembershipResources class return an empty json Array if no user in the group. This solve the issue by not making the js code fire an error and do unexpected stop.
