### ISSUE TITLE
[DPLM] Error while executing the dplm client with Ubuntu 14.04 LTS x64

### ISSUE THREAD

**Issue by LaurentLeVan** [docdoku/docdoku-plm#940]
An error occurred with the dplm client for Linux x64 and Ubuntu 14.04 LTS x64
`error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory`

I figure it out that since ubuntu 14.04 libudev.so.0 was removed. 

One way which work for me it to manually symlinked libudev.so.0 to libudev.so.1.

`cd /lib/x86_64-linux-gnu/
sudo ln -sf libudev.so.1 libudev.so.0`

I found the solution here : 
[http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error](url)

**Comment by mguimard** [comment]
Closing issue as it's related to NodeWebkit. 

See also
https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.1
