### ISSUE TITLE
javax.servlet.ServletException: Login failed on clean install

### ISSUE THREAD

**Issue by Billgator** [docdoku/docdoku-plm#945]
Hello,

Installed it, when i create a user i get the "javax.servlet.ServletException: Login failed" error.
The database IS filled with the information.

and normal login gives "DocdokuPLM failed to connect"

been searching for 2 days now no solution...

see log @ https://gist.github.com/anonymous/e7c144fb4fcb2f3a5c17

i used the ear version for install

**Comment by mguimard** [comment]
Hi there, 

Which version are you trying to deploy ? dev ? release.2-0 ?
What is the content of glassfish/domains/domain1/config/login.conf  ?

**Comment by Billgator** [comment]
i used the latest ear

and here's the login.conf → https://gist.github.com/Billgator/a5ddf2fa3cc72a59df96

**Comment by mguimard** [comment]
The docdokuRealm is missing in you login.conf, add at the end :

    docdokuRealm {
        com.sun.enterprise.security.ee.auth.login.JDBCLoginModule required; 
    };

**Comment by Billgator** [comment]
added the line but still no sigar

**Comment by mguimard** [comment]
Did you restart the server ?

**Comment by Billgator** [comment]
did the change before starting it

**Comment by powertieke** [comment]
https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide/d1f425c92da1a2a2261cbde50f4e0b269d6e0a3a#security

Use the old installation guide if you want to install the 2.0 stable .ear. Turns out the current install instructions are up to date with the development version.

**Comment by mguimard** [comment]
Closing the issue, please re open if needed.
