### ISSUE TITLE
[DPLM] Error while displaying parts catalogue

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#948]
on "DEMO" workspace only...

[failed to localize] Echec de la désérialisation de la réponse.(javax.xml.bind.UnmarshalException - with linked exception: [javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,32169] Message: Le contenu des éléments doit inclure un balisage ou des caractères au format correct.])

**Comment by mguimard** [comment]
Ahhh this is due to old data..

We have a cyclic link in BMX-014 < MSNBMX-014-A >, in the first iteration (this has been created before we decided to forbid this)

Then we'll have to clean it from DB manually, cause server will reject the deletion if we do it from GUI (it's in an assembly)

**Comment by mguimard** [comment]
https://github.com/docdoku/docdoku-plm/issues/951
