### ISSUE TITLE
[DPLM] Why not using the same filter approach on documents and parts ?

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#949]
Why not using the same filter approach on documents and parts ?
For documents we have only a dedicated tab for checkout parts.
For parts we have 4 available filters with checkbox.

**Comment by mguimard** [comment]
Right, this should be added, but we don't have released status on documents, they will be 3 filters on documents tab.

**Comment by mguimard** [comment]
All filters have been moved under the same menu.
