### ISSUE TITLE
[Workflow] Impossible to create a workflow

### ISSUE THREAD

**Issue by ericdescargues** [docdoku/docdoku-plm#967]
Error while creating a new workflow
![create-workflow](https://cloud.githubusercontent.com/assets/1931399/13630314/0848d12c-e5df-11e5-82ce-7ed09e029e8d.png)

**Comment by florentgarin** [comment]
The bug appears only on Chrome v49

**Comment by mguimard** [comment]
Still in chrome Version 50.0.2661.26 beta (64-bit) - Ubuntu 15.04
