### ISSUE TITLE
[Workspace Administration] Upgrading ACL for Read Only user

### ISSUE THREAD

**Issue by kelto** [docdoku/docdoku-plm#972]
Should we only allow the workspace administrator to upgrade the ACL for a read only user ?

**Comment by florentgarin** [comment]
At which level? Part and document?

Florent Garin (DocDoku)

**Comment by kelto** [comment]
I don't see any reason to make the parts, documents and  changement-management's item to differ in term of ACL management.

In term of level of ACL, the upgrade for a Read Only user can only be to full access.

**Comment by florentgarin** [comment]
I was not talking about that "level". I was talking about workspace level vs part/document level.
Actually, I did not understand the previous question: the question was if the administrator can upgrade rights or only the document/part owner?
