### ISSUE TITLE
CAD file can not be converted，How to install Convert Plugins?

### ISSUE THREAD

**Issue by creamjiang** [docdoku/docdoku-plm#975]
We have installed the ear file, but the CAD file can not be converted. How to install Convert Plugins? I'm in such a way https://github.com/docdoku/docdoku-plm/wiki/Convert-Plugins.

You can use a script file on the installation of a good environment.

**Comment by creamjiang** [comment]
need CATPart converter, CATProduct parser?

**Comment by florentgarin** [comment]
Which format do you want to support?

**Comment by creamjiang** [comment]
At present about the 3D format file can't display.
Need to support DWG format.
The best result is: You can use a script file on the installation of a good environment.

**Comment by florentgarin** [comment]
The DWG converter is not available on the open source distribution but as a complementary proprietary plugin.

**Comment by creamjiang** [comment]
How much is the enterprise version? If buy enterprise edition, you provide complete source code and technical support?
