### ISSUE TITLE
Installation Guide Improvement

### ISSUE THREAD

**Issue by PeerMueller** [docdoku/docdoku-plm#978]
I following your installation guide and ran into the following problems:
1. I did not download the "full" version of glassfish at first and was therefore unable to successfully deploy application ("There is no installed container capable of handling this application "). 
2. I did not start the database in glassfish "asadmin start-database" at first and was therefore unable to deploy the application ("Error connecting to server localhost on port 1527 with message Connection refused.").

These problems might be trivial to solve for people experienced with glassfish but for me these issues blocked me for quite some time. Maybe you could update the [https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide](url).

**Comment by mguimard** [comment]
Thank you for the feedback
I've added the "server full" info in the wiki. The second point (asadmin start-database) is not necessary. Closing issue.
