### ISSUE TITLE
[admin user] Create real PaaS administrator

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#983]
The admin role have to slightly changed to become a true PaaS admin role.
For instance, "admin" user should be able to manage all accounts, to disable them...
However, we should insure such user should not be allowed to have access to customer private data.

**Comment by florentgarin** [comment]
Moreover, we should add an application parameter that on/off superadmins operation validations.
For instance, a superadmin must validate each newly created account and newly created workspace.

**Comment by mguimard** [comment]
Super admin is now able to make such operations. Please reopen new issues for other super admin features
